import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:3100';
const production=process.env.EXPECT_PRODUCTION==='1';
const output=process.env.OUTPUT_DIR||'docs/verification/round3';
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const report={base,at:new Date().toISOString(),production,errors:[],harbour:[],places:[],round2Regressions:[]};
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 page.on('pageerror',error=>report.errors.push(error.message));
 page.on('console',message=>{if(message.type()==='error')report.errors.push(message.text())});
 page.on('response',response=>{if(response.status()>=400)report.errors.push(`${response.status()} ${response.url()}`)});
 await page.goto(`${base}/?city=dublin&place=dubHowthHarbour`,{waitUntil:'networkidle',timeout:60000});
 await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});
 const initial=await page.evaluate(()=>window.__mapExplorer.getSnapshot());
 assert.equal(initial.selectedId,'dubHowthHarbour','Howth deep link selects the new harbour');
 assert(!('metro' in initial)&&!('metro' in initial.dublinMetrics),'runtime snapshot has no metro state');
 assert.equal(await page.locator('.label[aria-label*="Metro"]').count(),0,'no metro label remains');
 assert.equal(await page.locator('.label[aria-label*="Dublin Metro"]').count(),0,'no old metro label remains');
 assert.equal(await page.evaluate(()=>typeof window.__mapExplorer.seekMetroSimulation),'undefined','no metro seek hook remains');
 if(production){assert.equal(await page.evaluate(()=>typeof window.__mapExplorer.seekDublinSimulation),'undefined','production has no deterministic seek state hook');assert.equal(await page.evaluate(()=>typeof window.__mapExplorer.stressCameraForVerification),'undefined','production has no camera stress hook');}
 assert(!initial.dublinMetrics.sceneObjectNames.some(name=>/metro/i.test(name)),'no metro-named scene geometry remains');
 await page.goto(`${base}/?city=dublin&place=dubMetroHeuston`,{waitUntil:'networkidle',timeout:60000});
 await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});
 const staleSelection=await page.evaluate(()=>window.__mapExplorer.getSnapshot());
 assert.equal(staleSelection.selectedId,null,'removed metro deep links do not create orphaned selection state');
 assert.equal(await page.locator('#detail:not([hidden])').count(),0,'removed metro deep links do not open a stale detail sheet');
 await page.goto(`${base}/?city=dublin&place=dubHowthHarbour`,{waitUntil:'networkidle',timeout:60000});
 await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});
 const metrics=(await page.evaluate(()=>window.__mapExplorer.getSnapshot())).dublinMetrics.city;
 assert(metrics.houseParcels>=250&&metrics.houseParcels<=350,`Round 3 housing parcels should be 250..350 (got ${metrics.houseParcels})`);
 assert(metrics.selectablePlaces>127,`Round 3 should expose more than 127 selectable Dublin destinations (got ${metrics.selectablePlaces})`);
 assert(initial.dublinMetrics.secondHarbour,'second harbour simulation metrics are available');
 assert(initial.dublinMetrics.roads.roadLanes>=8,'the road network includes the authored multi-lane system');
 assert.equal(initial.dublinMetrics.roads.connectivity.connected,true,'core, district, airport, port and Howth road routes form one physical network');
 assert.equal(initial.dublinMetrics.roads.connectivity.connectedComponents,1,'the physical road graph has one connected component');
 const namedVenues=initial.dublinMetrics.places.filter(place=>/^dubVenue/i.test(place.id));
 assert(namedVenues.length>=40,`new venue destinations should be included in the data (got ${namedVenues.length})`);
 const allowedKinds=new Set(['pub','cafe','market','retail','shoppingCentre','office','industry','hospital','education','musicVenue','sports','theatre','garden','civic','attraction']);
 assert(namedVenues.every(place=>allowedKinds.has(place.kind)),`new venues use the expected destination kinds: ${[...new Set(namedVenues.map(place=>place.kind))]}`);
 assert(new Set(namedVenues.map(place=>place.kind)).size>=8,'new venues span at least eight selectable destination categories');
 report.places={houseParcels:metrics.houseParcels,selectablePlaces:metrics.selectablePlaces,addedVenues:namedVenues.length,categories:metrics.placeCategories,roadMetrics:initial.dublinMetrics.roads,selectedVenueFocus:[]};
 const chosenIds=['dubVenuePoolbeg','dubVenueLiffeyValley','dubVenueInchicoreWorks','dubVenueGoogle','dubVenueCobblestone','dubVenueNationalStadium','dubVenueChiCrumlin','dubVenueBotanic'];
 const chosen=chosenIds.map(id=>namedVenues.find(place=>place.id===id));
 assert(chosen.every(Boolean),`the focused review set exists: ${chosenIds.filter((id,index)=>!chosen[index])}`);
 const focusOutput=path.join(output,'focus');await fs.mkdir(focusOutput,{recursive:true});
 for(const place of chosen){
   await page.goto(`${base}/?city=dublin&place=${encodeURIComponent(place.id)}`,{waitUntil:'networkidle',timeout:60000});
   await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});
   await page.locator('#detail:not([hidden])').waitFor();
   await page.locator('#focus').click();await page.waitForTimeout(720);
   const focused=await page.evaluate(()=>window.__mapExplorer.getSnapshot());
   assert.equal(focused.selectedId,place.id,`${place.name} deep link selects the destination`);
   assert(Math.hypot(focused.camera.target[0]-place.x,focused.camera.target[2]-place.z)<.05,`${place.name} camera focus targets its map position`);
   await page.locator('#close-detail').click();
   if(await page.locator('#names').getAttribute('aria-pressed')==='true')await page.locator('#names').click();await page.waitForTimeout(250);
   const screenshot=path.join(focusOutput,`${place.id}.png`);await page.screenshot({path:screenshot});
   report.places.selectedVenueFocus.push({id:place.id,name:place.name,kind:place.kind,focused:true,screenshot});
 }
 await page.goto(`${base}/?city=dublin&place=dubHowthHarbour`,{waitUntil:'networkidle',timeout:60000});
 await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});await page.locator('#detail:not([hidden])').waitFor();
 const selectedText=(await page.locator('#detail').innerText()).toLowerCase();
 assert(selectedText.includes('howth harbour'),'Howth sheet has its own status panel');
 assert(!selectedText.includes('cargo calls completed')&&!selectedText.includes('dispatch cargo ship'),'Howth sheet does not expose Dublin Port commerce');
 const getHarbour=()=>page.evaluate(()=>window.__mapExplorer.getSnapshot());
 const assertFiniteBoats=(state)=>{assert(state.secondHarbour.boats.length>0,'Howth has active boats');for(const boat of state.secondHarbour.boats){assert([boat.x,boat.z,boat.heading,boat.length,boat.width,boat.routeProgress].every(Number.isFinite),`finite pose for ${boat.id}`)}};
 assertFiniteBoats(initial);
 if(!production){
   await page.evaluate(()=>window.__mapExplorer.seekDublinSimulation(0));
   const zero=await getHarbour();assertFiniteBoats(zero);
   const moved=await page.evaluate(()=>window.__mapExplorer.seekDublinSimulation(15));assertFiniteBoats(moved);
   assert(moved.secondHarbour.boats.some((boat,index)=>Math.hypot(boat.x-zero.secondHarbour.boats[index]?.x,boat.z-zero.secondHarbour.boats[index]?.z)>.05),'Howth boats move on the shared deterministic clock');
   const pause=await page.evaluate(()=>{window.__mapExplorer.dispatchPort('pause');return window.__mapExplorer.getSnapshot()});
   await page.evaluate(()=>window.__mapExplorer.seekDublinSimulation(22));
   const frozen=await getHarbour();assert.equal(frozen.dublinClock.timeSeconds,pause.dublinClock.timeSeconds,'shared pause freezes Howth simulation');
   await page.evaluate(()=>window.__mapExplorer.dispatchPort('resume'));
   const resumed=await page.evaluate(()=>window.__mapExplorer.seekDublinSimulation(17));assert.equal(resumed.dublinClock.timeSeconds,17,'shared simulation resumes after pause and handles replay');
   await page.evaluate(()=>window.__mapExplorer.dispatchPort('reset'));
   const reset=await getHarbour();assert.equal(reset.dublinClock.timeSeconds,0,'reset rebases shared clock');assert.equal(reset.secondHarbour.timeSeconds,0,'reset rebases Howth boat clock');
   report.harbour.push({zero:zero.secondHarbour,moved:moved.secondHarbour,pausedAt:pause.dublinClock.timeSeconds,resumedAt:resumed.dublinClock.timeSeconds,resetAt:reset.secondHarbour.timeSeconds});
 }else{
   const before=await getHarbour();await page.waitForTimeout(1800);const moved=await getHarbour();assertFiniteBoats(moved);
   assert(moved.secondHarbour.boats.some((boat,index)=>Math.hypot(boat.x-before.secondHarbour.boats[index]?.x,boat.z-before.secondHarbour.boats[index]?.z)>.02),'Howth boats move in production');
   const pause=await page.evaluate(()=>{window.__mapExplorer.dispatchPort('pause');return window.__mapExplorer.getSnapshot()});await page.waitForTimeout(800);const frozen=await getHarbour();assert.equal(frozen.dublinClock.timeSeconds,pause.dublinClock.timeSeconds,'production shared pause freezes both harbours');
   const stillFrames=[];await page.waitForTimeout(300);for(let i=0;i<6;i++){stillFrames.push(await page.locator('canvas').screenshot());await page.waitForTimeout(100)}assert(stillFrames.every(frame=>frame.equals(stillFrames[0])),'paused production canvas remains stable across six captures');report.stablePausedFrames=6;
   await page.evaluate(()=>window.__mapExplorer.dispatchPort('resume'));await page.waitForTimeout(700);const resumed=await getHarbour();assert(resumed.secondHarbour.timeSeconds>frozen.secondHarbour.timeSeconds,'production shared resume advances Howth');
   await page.evaluate(()=>window.__mapExplorer.dispatchPort('reset'));const reset=await getHarbour();assert.equal(reset.secondHarbour.timeSeconds,0,'production reset clears Howth timeline');
   report.harbour.push({before:before.secondHarbour,moved:moved.secondHarbour,pausedAt:pause.dublinClock.timeSeconds,resumedAt:resumed.dublinClock.timeSeconds,resetAt:reset.secondHarbour.timeSeconds});
 }
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(150);const reducedBefore=await getHarbour();await page.waitForTimeout(450);const reducedAfter=await getHarbour();assert.equal(reducedAfter.secondHarbour.timeSeconds,reducedBefore.secondHarbour.timeSeconds,'reduced motion freezes Howth on the shared clock');await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForTimeout(300);const normalMotion=await getHarbour();if(production)assert(normalMotion.secondHarbour.timeSeconds>reducedAfter.secondHarbour.timeSeconds,'Howth resumes when reduced motion is disabled');report.reducedMotion={frozenAt:reducedAfter.secondHarbour.timeSeconds,resumedAt:normalMotion.secondHarbour.timeSeconds};
 assert.deepEqual(report.errors,[],'Round 3 browser should not produce errors');
 await page.locator('#focus').click();await page.waitForTimeout(720);await page.locator('#close-detail').click();
 const namesButton=page.locator('#names');if(await namesButton.getAttribute('aria-pressed')==='true')await namesButton.click();await page.waitForTimeout(250);
 await page.screenshot({path:path.join(output,'howth-harbour.png')});
 await namesButton.click();await page.waitForTimeout(250);await page.screenshot({path:path.join(output,'howth-harbour-names.png')});
 await page.goto(`${base}/?city=dublin`,{waitUntil:'networkidle',timeout:60000});await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});
 const overviewNames=page.locator('#names');if(await overviewNames.getAttribute('aria-pressed')==='true')await overviewNames.click();await page.waitForTimeout(250);
 await page.screenshot({path:path.join(output,'dublin-overview.png')});
 await overviewNames.click();await page.waitForTimeout(250);await page.screenshot({path:path.join(output,'dublin-overview-names.png')});
 await page.goto(`${base}/?city=dublin&place=dubHowthHarbour`,{waitUntil:'networkidle',timeout:60000});await page.locator('#map[data-ready="true"]').waitFor({timeout:60000});
 await page.locator('#walk-here').click();await page.waitForTimeout(250);
 const walkStart=await page.evaluate(()=>window.__mapExplorer.getSnapshot());assert(walkStart.state.walking&&walkStart.walker.every(Number.isFinite),'Howth supports finite walking state');assert(Math.abs(walkStart.walker[1]-.28)<1e-6,'Howth walker meets the actual raised quay');assert(Math.abs(walkStart.walker[0]-65.5)<.01&&Math.abs(walkStart.walker[2]+45.8)<.01,'Howth walk arrival is on its authored quay');await page.locator('#leave-walk').click();report.harbourWalk={arrival:walkStart.walker,exited:!(await page.evaluate(()=>window.__mapExplorer.getSnapshot())).state.walking};
 await fs.writeFile(path.join(output,'browser-report.json'),JSON.stringify(report,null,2));
 console.log(`Round 3 passed: ${metrics.selectablePlaces} destinations, ${metrics.houseParcels} housing parcels, Howth shared-clock lifecycle`);
}finally{await browser.close()}
