import * as THREE from 'three';
import {MapControls} from 'three/addons/controls/MapControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {buildAbuja} from './abuja.js';
import {buildDublin,DUBLIN_BACKGROUND} from './dublin.js';

const $=id=>document.getElementById(id), host=$('map');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
renderer.setClearColor('#67afd5');host.appendChild(renderer.domElement);
renderer.domElement.setAttribute('aria-label','3D city map. Drag to pan, scroll to zoom.');
renderer.domElement.tabIndex=0;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,900);
const controls=new MapControls(camera,renderer.domElement);
controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=7;controls.maxDistance=110;
controls.maxPolarAngle=Math.PI*.44;controls.minPolarAngle=.18;controls.screenSpacePanning=false;
camera.position.set(3.75,37.5,26.25);controls.target.set(2.25,0,1.5);
scene.add(new THREE.HemisphereLight('#eaf4ff','#c9b99a',.9));
const sun=new THREE.DirectionalLight('#ffffff',1.6);sun.position.set(32,56,24);sun.castShadow=true;
sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-50,right:50,top:50,bottom:-50,near:1,far:120});
sun.shadow.normalBias=.035;sun.shadow.bias=-.0002;scene.add(sun);
const materials=new Map(), modelCache=new Map(), loader=new GLTFLoader();
const world=new THREE.Group(), estate=new THREE.Group(), boards=new THREE.Group();scene.add(world,estate,boards);
const mat=color=>{if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.95}));return materials.get(color)};
function box(parent,x,y,z,w,h,d,color){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));mesh.position.set(x,y,z);mesh.castShadow=h>.15;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function cylinder(parent,x,y,z,r,h,color,r2=r,segments=12){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r2,h,segments),mat(color));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function dome(parent,x,y,z,r,color){const m=new THREE.Mesh(new THREE.SphereGeometry(r,20,10,0,Math.PI*2,0,Math.PI/2),mat(color));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
function textSurface(text,color,w,parent,x,y,z,flat=true,bg=null){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=flat?128:384;const ctx=canvas.getContext('2d');if(bg){ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';let size=flat?90:94;do{ctx.font=`800 ${size}px Arial`;size-=2}while(ctx.measureText(text).width>950&&size>16);ctx.fillText(text,512,canvas.height/2);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,w*canvas.height/1024),new THREE.MeshBasicMaterial({map:texture,transparent:!bg,depthWrite:!!bg,side:THREE.DoubleSide}));if(flat)mesh.rotation.x=-Math.PI/2;mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
function road(x,z,w,d){box(world,x,.211,z,w,.023,d,'#969c9f');}
// The coast, lot coordinates, and road network follow the reference map.
box(world,25,-.16,-20,250,.1,230,'#67afd5');
[[0,-11.4,42,18,'#a7cc86'],[-4.275,7.65,25.05,13.5,'#c7e0a5'],[15,7.5,12.9,13.8,'#c7e0a5'],[5.1,-.75,2.7,2.5,'#c7e0a5'],[6,15.3,34.5,2.7,'#ecd9a6'],[8.25,18.525,33.9,3.6,'#d9dccf'],[-23.85,-11.4,6,18,'#a7cc86']].forEach(([x,z,w,d,c])=>box(world,x,.05,z,w,.3,d,c));
textSurface('MAINLAND','#759a58',8,world,-12,.217,-17.4);
textSurface('ISLAND','#93ad73',6,world,-9,.217,1.5);
textSurface('LAGOS LAGOON','#d0e8f2',8,world,11.4,.01,-.9);
textSurface('ATLANTIC OCEAN','#c3e2ef',12,world,23,.01,23);
textSurface('EKO ATLANTIC','#82917e',7,world,11,.217,18.7);
[[0,-4.5,33,.5],[-1.2,2.175,.5,2.55],[-4.575,2.4,22.65,.5],[12.75,6,8.7,.5],[8.25,19.575,33,.42],[-23.1,-11.4,.45,17.4]].forEach(args=>road(...args));
function bridge(x,z,length,across=false,cable=false){const g=new THREE.Group();g.position.set(x,0,z);if(across)g.rotation.y=Math.PI/2;world.add(g);box(g,0,.29,0,.52,.13,length,'#a1a7ab');for(const side of [-1,1]){box(g,side*.3,.43,0,.045,.13,length,'#c5c8ca');for(let i=-length/2+.25;i<length/2;i+=.6)cylinder(g,side*.22,-.15,i,.04,.8,'#999e9c');}if(cable){for(let z of [-length*.3,length*.3]){box(g,0,1.5,z,.08,2.5,.08,'#eee6d6');for(let k of [-1,1]){const p=[new THREE.Vector3(0,2.6,z),new THREE.Vector3(0,.4,z+k*length*.35)];g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),new THREE.LineBasicMaterial({color:'#e2dfd2'})));}}}return g;}
bridge(-1.2,-.75,3.3);bridge(7.95,6,1.2,true,true);
const modelPaths=async path=>{if(!modelCache.has(path))modelCache.set(path,loader.loadAsync(`assets/${path}.glb`).then(g=>g.scene));return modelCache.get(path)};
async function addModel(parent,path,height,pos=[0,0,0],tint=null,rotation=0){const original=await modelPaths(path), object=original.clone(true);object.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;if(tint){n.material=n.material.clone();n.material.color.set(tint)}}});const bounds=new THREE.Box3().setFromObject(object),center=bounds.getCenter(new THREE.Vector3()),factor=height/(bounds.getSize(new THREE.Vector3()).y||1);object.position.set(-center.x,-bounds.min.y,-center.z);const group=new THREE.Group();group.add(object);group.scale.setScalar(factor);group.position.set(...pos);group.rotation.y=rotation;parent.add(group);return group;}
const data=await fetch('places.json').then(r=>{if(!r.ok)throw Error('Map data could not load');return r.json()});
data.push({id:'airport',name:'Airport',x:-35,z:-12,w:21,d:19,h:2,models:[]},{id:'refinery',name:'Refinery',x:-25,z:8,w:13,d:13,h:2.6,models:[]});
const emoji={shrine:'🎷',viewingCentre:'⚽',mamaPut:'🍲',yabaHub:'💡',balogun:'🧺',freedomPark:'🎭',ikoyiGym:'🏋️',office:'🏢',clubEko:'🪩',lcc:'🌉',mall:'🛍️',library:'📚',elegushi:'🏖️',hospital:'🏥',salon:'💇🏾‍♀️',rooftop:'🕯️',policeStation:'🚓',church:'⛪',mosque:'🕌',naijaRadio:'📻',pollingUnit:'🗳️',ekoHotel:'🏨',polanco:'🚘',boatCruise:'⛵',golfClub:'⛳',courthouse:'⚖️',unilag:'🎓',casino:'🎰',mindSpace:'🫶🏾',stadium:'🏟️',ojuelegba:'🎱'};
const descriptions={shrine:'Music and nightlife on the Mainland.',yabaHub:'The technology hub in Yaba.',balogun:'Colourful market stalls on Lagos Island.',lcc:'Forest trails and an elevated canopy walkway.',elegushi:'The sandy shoreline on the Atlantic.',unilag:'University buildings, gardens, and sports courts.',freedomPark:'Gardens and paths in the heart of the Island.',golfClub:'A green course beside the Lekki–Ikoyi Link.',boatCruise:'The dock on Lagos Lagoon.',ekoHotel:'The hotel grounds on Lagos Island.',stadium:'A football stadium on the Mainland.'};
let selected=null,showNames=true,showHomes=true,showBoards=true,walking=false,transition=null,activeCity='lagos';
data.forEach(p=>p.city='lagos');host.dataset.city=activeCity;
const labels=[], tasks=[];let settled=0;
function task(p){tasks.push(p.catch(e=>{console.warn(e);return null}).finally(()=>{settled++;$('progress').textContent=`Building the city · ${Math.round(settled/tasks.length*100)}%`;$('loadbar').style.width=`${settled/tasks.length*100}%`;}));}
function sign(parent,text,x,y,z,w=1.2){textSurface(text,'#ffffff',w,parent,x,y,z,false,'#008751')}
function garden(g,w,d){box(g,0,.008,0,w,.025,d,'#8aba65');box(g,0,.025,0,.12,.02,d,'#d5ccaa');box(g,0,.025,0,w,.02,.12,'#d5ccaa');}
function special(p,g){const id=p.id;
 if(id==='airport'){box(g,0,-.015,0,21,.05,19,'#afb59d');box(g,0,.03,-6,20,.04,2.3,'#50595c');for(let i=-9;i<10;i+=1.2)box(g,i,.055,-6,.6,.015,.07,'#ecebd8');box(g,0,.03,-2,20,.04,1.2,'#95998e');box(g,0,.6,3,9,1.2,3,'#dce2dc');box(g,0,1.23,3,9.3,.08,3.2,'#838f94');box(g,0,.6,4.51,8,.6,.025,'#73a1b4');cylinder(g,-6,1.3,3,.22,2.6,'#dce0dd');box(g,-6,2.7,3,.8,.5,.7,'#6e9eae');for(let i=0;i<4;i++){const plane=new THREE.Group();plane.position.set(-6+i*4,.5,.1);g.add(plane);const fuselage=cylinder(plane,0,0,0,.13,2,'#f0f0e7',.08);fuselage.rotation.x=Math.PI/2;box(plane,0,0,0,1.9,.045,.4,'#e9ebe3');box(plane,0,.09,.7,.05,.35,.4,'#97afb8');box(plane,0,0,.7,.7,.04,.2,'#e5e9e0');}sign(g,'LAGOS AIRPORT',0,1,4.54,3);}
 if(id==='refinery'){box(g,0,-.015,0,13,.05,13,'#c9c6b7');for(let i=0;i<5;i++){const x=-4.6+i*2.25;cylinder(g,x,.8,-3,.9,1.6,'#d7d7ce');dome(g,x,1.6,-3,.9,'#c6c9c3');cylinder(g,x,.5,0,.85,1,'#bfc4bf');}for(let i=0;i<3;i++){cylinder(g,-4+i*2.2,1.8,3,.35,3.6,'#c7c9c1');for(let y=.5;y<3.6;y+=.55)cylinder(g,-4+i*2.2,y,3,.41,.05,'#dfc05c');}box(g,3,.7,3,3,1.4,2.3,'#969b93');for(let i=0;i<2;i++)cylinder(g,2.5+i,2.3,3,.17,3.5,'#c1c4ba');for(let i=0;i<5;i++)box(g,-4+i*2.1,.4,4.9,1.8,.09,.09,'#9d8d57');sign(g,'REFINERY',0,.8,5.9,2.6);}
 if(id==='mosque'){box(g,0,.35,0,1.1,.7,1,'#f4efe6');dome(g,0,.7,0,.38,'#059669');cylinder(g,.62,.65,.4,.09,1.3,'#f4efe6',.11);dome(g,.62,1.3,.4,.11,'#059669');}
 if(id==='courthouse'){box(g,0,.04,0,1.5,.08,1.15,'#d6d3cc');box(g,0,.43,-.12,1.3,.7,.8,'#f4efe6');for(let x=-.5;x<=.5;x+=.25)cylinder(g,x,.39,.4,.045,.62,'#f8fafc');box(g,0,.74,.02,1.42,.08,.98,'#e7e0d2');const roof=new THREE.Mesh(new THREE.ConeGeometry(.86,.32,4),mat('#7c2d12'));roof.position.set(0,.94,.02);roof.rotation.y=Math.PI/4;g.add(roof);sign(g,'HIGH COURT',0,.74,.52);}
 if(id==='church'){box(g,0,1.35,0,.06,.42,.06,'#e3be60');box(g,0,1.42,0,.24,.06,.06,'#e3be60');}
 if(id==='hospital'){box(g,0,1.62,0,.5,.12,.14,'#e5484d');box(g,0,1.62,0,.14,.12,.5,'#e5484d');}
 if(id==='library'||id==='mindSpace'||id==='naijaRadio'||id==='casino'){const library=id==='library',casino=id==='casino';box(g,0,library?.55:.4,-.1,1.2,library?1.1:.8,1,library?'#6d5a9c':casino?'#2a1838':'#e8f3ec');box(g,0,library?1.13:.83,-.1,1.28,.06,1.08,library?'#b9a8e6':'#52b788');box(g,0,.3,.41,.95,.26,.02,'#bde0fe');sign(g,p.name.toUpperCase(),0,.65,.43);if(casino)dome(g,0,.85,-.1,.36,'#c9a227');if(id==='naijaRadio'){cylinder(g,.85,1.3,0,.025,2.6,'#a4a9ae');for(let i=0;i<3;i++)box(g,.85,1.5+i*.4,0,.45,.025,.03,'#b9c0c5');}}
 if(id==='pollingUnit'){for(const x of [-.55,.55])for(const z of [-.4,.4])cylinder(g,x,.32,z,.02,.64,'#cbd5e1');[-.45,-.15,.15,.45].forEach((x,i)=>box(g,x,.68,0,.3,.06,.95,i%2?'#ffffff':'#008751'));box(g,0,.22,0,.8,.04,.4,'#8b6a4a');sign(g,'POLLING UNIT',0,.5,.52);}
 if(id==='mall'){box(g,0,.53,0,2.5,1.05,1.5,'#f4efe6');box(g,0,1.08,0,2.7,.12,1.7,'#e0e3df');for(const x of [-.75,0,.75])box(g,x,.35,.76,.45,.7,.03,'#273c4c');sign(g,'THE PALMS',0,.88,.8,1.7);}
 if(id==='balogun'){const colors=['#efb23b','#279ea1','#535ac0','#d83f58','#54a861'];for(let x=0;x<5;x++)for(let z=0;z<3;z++){box(g,(x-2)*.76,.4,z*.76-.4,.7,.07,.72,colors[(x+z)%5]);box(g,(x-2)*.76,.17,z*.76-.4,.65,.32,.64,'#b59768');}}
 if(id==='freedomPark'||id==='golfClub'||id==='ekoHotel'){garden(g,p.w,p.d);if(id==='ekoHotel'){box(g,-.8,.032,.7,1.3,.025,.75,'#52bcd5');for(let i=0;i<4;i++)task(addModel(g,'commercial/detail-parasol-a',.35,[-1.4+i*.7,0,1.35]));}if(id==='golfClub'){box(g,.55,.03,0,.75,.02,.45,'#69bdd7');for(const x of [-1,1]){cylinder(g,x,.42,-1.2,.01,.8,'#f3f1e1');box(g,x+.09,.76,-1.2,.18,.13,.02,'#e24646');}}}
 if(id==='unilag'){garden(g,p.w,p.d);box(g,1.8,.03,1.2,2.5,.02,1.5,'#bc5e3c');box(g,1.8,.047,1.2,2,.015,1,'#7ead62');box(g,-.8,.03,1.25,2,.02,1.4,'#688f55');for(let i=0;i<6;i++)task(addModel(g,'suburban/tree-small',.65,[-3+i*1.15,0,2.1]));}
 if(id==='lcc'){box(g,0,.012,0,6.7,.035,3.8,'#81ab60');for(let i=0;i<27;i++){let x=(Math.sin(i*127.1)*.5+.5)*5.8-2.9,z=(Math.cos(i*61.3)*.5+.5)*3.3-1.65;task(addModel(g,i%3?'suburban/tree-small':'suburban/tree-large',1+((i*7)%9)*.08,[x,0,z]));}for(let i=0;i<3;i++){let b=box(g,-1.9+i*1.5,.95,-.5+i*.55,1.7,.045,.25,'#aa8b5a');b.rotation.y=-.35;for(let x of [-2.6+i*1.5,-1.2+i*1.5])cylinder(g,x,.58,-.5+i*.55,.025,1.12,'#9a7c49');}sign(g,'CANOPY WALK',-2.5,.27,1.7,1.5);}
 if(id==='elegushi'){for(let i=0;i<9;i++)task(addModel(g,`commercial/detail-parasol-${i%2?'a':'b'}`,.55,[-2.6+i*.65,0,.45]));sign(g,'ELEGUSHI',-1.5,.28,-.35);}
 if(id==='stadium'){box(g,0,.02,0,2.4,.04,1.4,'#3f8f3a');box(g,0,.05,0,.025,.008,1.4,'#fff');const ring=new THREE.Mesh(new THREE.CylinderGeometry(1.55,1.2,.45,40,1,true),new THREE.MeshStandardMaterial({color:'#c6d9ca',side:THREE.DoubleSide}));ring.scale.z=.7;ring.position.y=.27;g.add(ring);for(let x of [-1.65,1.65])for(let z of [-.95,.95]){cylinder(g,x,.7,z,.022,1.4,'#a4a9ae');box(g,x,1.4,z,.32,.13,.08,'#fffae5');}sign(g,'STADIUM',0,.33,1.14);}
 if(id==='boatCruise'){task(addModel(g,'pirate/boat-row-small',.35,[.4,.03,.4]));}
}
for(const place of data){if(place.id.startsWith('home_')&&place.id!=='home_yaba')continue;const g=new THREE.Group();g.position.set(place.x,.205,place.z);world.add(g);place.group=g;box(g,0,-.012,0,place.w,.03,place.d,'#e4e5d6');special(place,g);for(const model of place.models)task(addModel(g,model.model,model.height,model.position,model.tint));const button=document.createElement('button');button.className='label';button.innerHTML=`<span>${emoji[place.id]||(place.id==='airport'?'✈️':place.id==='refinery'?'🛢️':'🏠')}</span>${place.name}`;button.setAttribute('aria-label',`Select ${place.name}`);button.onclick=()=>selectPlace(place);$('labels').appendChild(button);labels.push({place,button,point:new THREE.Vector3(place.x,.205+place.h,place.z)});}
const abuja=buildAbuja({box,textSurface});scene.add(abuja.world);data.push(...abuja.places);
const dublin=buildDublin({textSurface});scene.add(dublin.world);data.push(...dublin.places);
for(const place of [...abuja.places,...dublin.places]){const button=document.createElement('button');button.className='label';button.hidden=true;button.innerHTML=`<span>${place.emoji}</span>${place.name}`;button.setAttribute('aria-label',`Select ${place.name}`);button.onclick=()=>selectPlace(place);$('labels').appendChild(button);const offset=place.tag||[0,place.h,0];labels.push({place,button,point:new THREE.Vector3(place.x+offset[0],.28+offset[1],place.z+offset[2])});}
const labelPriority={dubHapenny:110,dubTrinity:109,dubSpire:108,dubAirport:107,dubGreen:106,dubGuinness:105,dubBeckett:104,dubTemple:103,abjAssembly:100,abjAsoRock:99,abjAirport:98,abjJabiLake:97,abjZumaRock:96,abjMosque:95,abjMillenniumPark:90};labels.sort((a,b)=>(labelPriority[b.place.id]||0)-(labelPriority[a.place.id]||0));
// Repeated housing plots are visual map scenery, without player data.
box(estate,0,.055,-25,42,.3,7.5,'#add08f');box(estate,19,.055,9.4,8,.3,12,'#c7e0a5');
for(let row=0;row<4;row++)for(let col=0;col<22;col++){const x=-20+col*1.85,z=-27.8+row*1.75;box(estate,x,.219,z,1.4,.03,1.4,'#e4e6d8');task(addModel(estate,'suburban/building-type-c',.62,[x,.24,z]));}
for(let row=0;row<7;row++)for(let col=0;col<4;col++){const x=16.25+col*1.65,z=4.4+row*1.65;box(estate,x,.219,z,1.4,.03,1.4,'#e6e7dc');task(addModel(estate,'suburban/building-type-t',.64,[x,.24,z]));}
for(const [i,x,z] of [[0,-15,-15],[1,-16,-7],[2,-8,-3.5],[3,1,-3.8],[4,14,-4],[5,-3,.1],[6,16,1],[7,12,7.5],[8,-8,10.5],[9,2,14.4],[10,18,13.8]]){box(boards,x,1.55,z,3.3,1.7,.11,'#202431');for(const dx of [-1.3,1.3])box(boards,x+dx,.75,z,.09,1.5,.09,'#202431');textSurface(i%2?'LAGOS LIFE':'YOUR AD HERE','#fff',3.13,boards,x,1.55,z+.067,false,i%2?'#206b57':'#276998');}
for(let i=0;i<28;i++){const x=-17+((i*13)%38),z=i%2?-4.9:14.3;task(addModel(world,'pirate/palm-straight',1.1,[x,.205,z]));}
const traffic=[];for(let i=0;i<5;i++){const group=new THREE.Group();world.add(group);group.position.set(-15+i*7,.24,-4.5);task(addModel(group,i%2?'car/sedan':'car/van',.26,[0,0,0],i%2?null:'#f3c43d',Math.PI/2));traffic.push(group);}
const marker=new THREE.Group();marker.visible=false;scene.add(marker);cylinder(marker,0,.04,0,.2,.06,'#54af7d');cylinder(marker,0,.6,0,.13,.55,'#252e43');dome(marker,0,.92,0,.14,'#a77750');box(marker,-.1,.23,0,.065,.4,.09,'#252e43');box(marker,.1,.23,0,.065,.4,.09,'#252e43');
marker.position.set(.75,.22,-6);let walkTarget=null,keys=new Set(),lastTime=0;
const selectionRing=new THREE.Mesh(new THREE.RingGeometry(.95,1.03,48),new THREE.MeshBasicMaterial({color:'#408b61',side:THREE.DoubleSide,transparent:true,opacity:.75}));selectionRing.rotation.x=-Math.PI/2;selectionRing.visible=false;scene.add(selectionRing);
const cityViews={lagos:{position:new THREE.Vector3(3.75,37.5,26.25),target:new THREE.Vector3(2.25,0,1.5)},abuja:{position:new THREE.Vector3(-2,88,68).sub(new THREE.Vector3(-2,0,2)).multiplyScalar(Math.max(1.7,1.8/camera.aspect)).add(new THREE.Vector3(-2,0,2)),target:new THREE.Vector3(-2,0,2)}};
cityViews.dublin={position:new THREE.Vector3(5,73,61).multiplyScalar(Math.max(1.45,1.55/camera.aspect)),target:new THREE.Vector3(0,0,-5)};
const cityCameras={};
const cityNames={lagos:'🇳🇬 Lagos',abuja:'🇳🇬 Abuja',dublin:'🇮🇪 Dublin'};
function switchCity(city){
 if(!['lagos','abuja','dublin'].includes(city))throw new Error('Unknown map city');
 if(city===activeCity)return {city,changed:false};
 cityCameras[activeCity]={position:camera.position.clone(),target:controls.target.clone()};
 walking=false;marker.visible=false;walkTarget=null;keys.clear();controls.enableRotate=true;transition=null;clearSelection();
 $('walk').setAttribute('aria-pressed','false');$('walk-controls').hidden=true;$('hint').hidden=false;
 activeCity=city;world.visible=city==='lagos';estate.visible=city==='lagos'&&showHomes;boards.visible=city==='lagos'&&showBoards;abuja.world.visible=city==='abuja';abuja.homes.visible=showHomes;abuja.boards.visible=showBoards;dublin.world.visible=city==='dublin';dublin.homes.visible=showHomes;dublin.boards.visible=showBoards;
 renderer.setClearColor(city==='abuja'?'#93b56c':city==='dublin'?DUBLIN_BACKGROUND:'#67afd5');host.dataset.city=city;$('city-name').textContent=cityNames[city];
 host.setAttribute('aria-label',`Interactive 3D ${city[0].toUpperCase()+city.slice(1)} city map`);
 document.querySelectorAll('button[data-city]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.city===city)));
 const tabs=city==='dublin'?[['all','🗺️','All Dublin'],['centre','🏛️','City centre'],['northside','🏘️','Northside'],['docklands','⚓','Docklands']]:city==='abuja'?[['all','🗺️','All Abuja'],['central','🏛️','Central'],['maitama','🌳','Maitama'],['jabi','🌊','Jabi']]:[['all','🗺️','All Lagos'],['mainland','🏘️','Mainland'],['island','🏙️','Island'],['lekki','🌴','Lekki']];
 document.querySelectorAll('[data-district]').forEach((button,i)=>{button.dataset.district=tabs[i][0];button.innerHTML=`${tabs[i][1]}<span>${tabs[i][2]}</span>`;button.classList.toggle('active',i===0);});
 controls.maxDistance=city==='lagos'?110:500;controls.minDistance=city==='lagos'?7:12;
 const view=cityCameras[city]||cityViews[city];camera.position.copy(view.position);controls.target.copy(view.target);controls.update();
 sun.position.set(city==='lagos'?32:40,city==='lagos'?56:90,city==='lagos'?24:28);const extent=city==='lagos'?50:95;Object.assign(sun.shadow.camera,{left:-extent,right:extent,top:extent,bottom:-extent,far:city==='lagos'?120:230});sun.shadow.camera.updateProjectionMatrix();
 marker.position.set(city==='lagos'?.75:0,.28,city==='lagos'?-6:city==='dublin'?5:0);
 return {city,changed:true};
}
document.querySelectorAll('button[data-city]').forEach(button=>button.onclick=()=>switchCity(button.dataset.city));
function district(p){return p.city!=='lagos'?p.area:p.z< -2?'Mainland':p.x>8?'Lekki':'Island';}
function selectPlace(p){if(p.city!==activeCity)switchCity(p.city);selected=p;labels.forEach(l=>l.button.classList.toggle('selected',l.place===p));$('detail').hidden=false;$('place-name').textContent=`${p.emoji||emoji[p.id]||'🏠'} ${p.name}`;$('district').textContent=district(p);$('place-desc').textContent=p.description||descriptions[p.id]||(p.city==='abuja'?`${p.name} in ${p.area}. Explore the landmark and its surroundings on the Abuja map.`:`${p.name} on the ${district(p)} side of the city.`);selectionRing.position.set(p.x,p.city==='lagos'?.23:.33,p.z);selectionRing.scale.setScalar(p.city!=='lagos'?Math.max(1,Math.min(p.w,p.d)*.55):1);selectionRing.visible=true;}
function clearSelection(){selected=null;$('detail').hidden=true;selectionRing.visible=false;labels.forEach(l=>l.button.classList.remove('selected'));}
function flyTo(x,z,distance=20){const direction=camera.position.clone().sub(controls.target).normalize();transition={from:camera.position.clone(),fromTarget:controls.target.clone(),to:new THREE.Vector3(x,0,z).addScaledVector(direction,distance),toTarget:new THREE.Vector3(x,0,z),start:performance.now()};}
function toggleWalk(value=!walking){walking=value;marker.visible=value;controls.enableRotate=!value;$('walk').setAttribute('aria-pressed',String(value));$('walk-controls').hidden=!value;$('hint').hidden=value;walkTarget=null;keys.clear();if(value)flyTo(marker.position.x,marker.position.z,12);else resetView();}
function resetView(){if(walking){walking=false;marker.visible=false;controls.enableRotate=true;$('walk').setAttribute('aria-pressed','false');$('walk-controls').hidden=true;$('hint').hidden=false;keys.clear();}transition={from:camera.position.clone(),fromTarget:controls.target.clone(),to:cityViews[activeCity].position.clone(),toTarget:cityViews[activeCity].target.clone(),start:performance.now()};document.querySelectorAll('[data-district]').forEach(b=>b.classList.toggle('active',b.dataset.district==='all'));}
function zoom(factor){transition=null;camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);const dist=camera.position.distanceTo(controls.target);if(dist<controls.minDistance||dist>controls.maxDistance)camera.position.sub(controls.target).normalize().multiplyScalar(THREE.MathUtils.clamp(dist,controls.minDistance,controls.maxDistance)).add(controls.target);controls.update();}
$('names').onclick=()=>{showNames=!showNames;$('names').setAttribute('aria-pressed',String(showNames));};
$('homes').onclick=()=>{showHomes=!showHomes;estate.visible=activeCity==='lagos'&&showHomes;abuja.homes.visible=showHomes;dublin.homes.visible=showHomes;$('homes').setAttribute('aria-pressed',String(showHomes));};
$('boards').onclick=()=>{showBoards=!showBoards;boards.visible=activeCity==='lagos'&&showBoards;abuja.boards.visible=showBoards;dublin.boards.visible=showBoards;$('boards').setAttribute('aria-pressed',String(showBoards));};
$('walk').onclick=()=>toggleWalk();$('leave-walk').onclick=()=>toggleWalk(false);
$('plus').onclick=()=>zoom(.8);$('minus').onclick=()=>zoom(1.25);$('reset').onclick=resetView;
$('close-detail').onclick=clearSelection;$('focus').onclick=()=>selected&&flyTo(selected.x,selected.z,10);
$('walk-here').onclick=()=>{if(!selected)return;const p=selected;toggleWalk(true);marker.position.set(p.arrivalX??p.x,.22,p.arrivalZ??(p.z+p.d/2+.65));flyTo(marker.position.x,marker.position.z,12);clearSelection();};
document.querySelectorAll('[data-district]').forEach(button=>button.onclick=()=>{clearSelection();if(walking)toggleWalk(false);document.querySelectorAll('[data-district]').forEach(b=>b.classList.toggle('active',b===button));const targets=activeCity==='dublin'?{centre:[-5,12,39],northside:[-7,-20,55],docklands:[28,5,42]}:activeCity==='abuja'?{central:[16,0,45],maitama:[22,-32,43],jabi:[-35,-10,45]}:{mainland:[0,-12,28],island:[-4,7.5,25],lekki:[15,8,24]};if(button.dataset.district==='all')resetView();else flyTo(...targets[button.dataset.district]);});
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
controls.addEventListener('start',()=>transition=null);
window.addEventListener('keydown',e=>{if(e.key==='Escape'){clearSelection();if(walking)toggleWalk(false);}if(walking&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);}});
window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());
const moveMap={up:'w',down:'s',left:'a',right:'d'};document.querySelectorAll('[data-move]').forEach(button=>{button.addEventListener('pointerdown',e=>{button.setPointerCapture(e.pointerId);keys.add(moveMap[button.dataset.move]);});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>keys.delete(moveMap[button.dataset.move]));});
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(), ground=new THREE.Plane(new THREE.Vector3(0,1,0),-.22);let pressStart=null;
renderer.domElement.addEventListener('pointerdown',e=>pressStart=[e.clientX,e.clientY]);
renderer.domElement.addEventListener('pointerup',e=>{if(!pressStart||Math.hypot(e.clientX-pressStart[0],e.clientY-pressStart[1])>7)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const point=new THREE.Vector3();if(!raycaster.ray.intersectPlane(ground,point))return;if(walking){walkTarget=point;return;}const closest=data.filter(p=>p.city===activeCity&&Math.abs(p.x-point.x)<p.w/2+.3&&Math.abs(p.z-point.z)<p.d/2+.3).sort((a,b)=>Math.hypot(a.x-point.x,a.z-point.z)-Math.hypot(b.x-point.x,b.z-point.z))[0];if(closest)selectPlace(closest);else clearSelection();});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);cityViews.abuja.position.set(-2,88,68).sub(cityViews.abuja.target).multiplyScalar(Math.max(1.7,1.8/camera.aspect)).add(cityViews.abuja.target);cityViews.dublin.position.set(5,73,61).multiplyScalar(Math.max(1.45,1.55/camera.aspect))});
function isLand(x,z){if(activeCity==='dublin')return dublin.isLand(x,z);if(activeCity==='abuja')return x>-64&&x<60&&z>-47&&z<48&&((x+36)/8)**2+((z+9)/5)**2>1&&Math.hypot(x-52,z+1)>8&&Math.hypot(x+56,z+8)>6;return (x>-21&&x<21&&z>-20.4&&z< -2.4)||(x>-26.9&&x<-20.8&&z>-20.4&&z< -2.4)||(x>-16.8&&x<8.25&&z>.9&&z<14.4)||(x>8.55&&x<23.1&&z>.6&&z<14.4)||(x>-11.25&&x<25.7&&z>13.8&&z<20.3)||(Math.abs(x+1.2)<.33&&z>-2.4&&z<.9)||(x>7.9&&x<8.6&&Math.abs(z-6)<.35);}
const projection=new THREE.Vector3();const mobile=()=>innerWidth<700;
function frame(time){const delta=Math.min((time-lastTime)/1000,.05)||0;lastTime=time;
 if(transition){let t=Math.min((time-transition.start)/650,1),ease=t*t*(3-2*t);camera.position.lerpVectors(transition.from,transition.to,ease);controls.target.lerpVectors(transition.fromTarget,transition.toTarget,ease);if(t===1)transition=null;}
 if(walking){let x=0,z=0;const forward=new THREE.Vector3().subVectors(controls.target,camera.position);forward.y=0;forward.normalize();const right=new THREE.Vector3(-forward.z,0,forward.x);if(keys.has('w')||keys.has('ArrowUp')){x+=forward.x;z+=forward.z}if(keys.has('s')||keys.has('ArrowDown')){x-=forward.x;z-=forward.z}if(keys.has('d')||keys.has('ArrowRight')){x+=right.x;z+=right.z}if(keys.has('a')||keys.has('ArrowLeft')){x-=right.x;z-=right.z}if(x||z)walkTarget=null;else if(walkTarget){x=walkTarget.x-marker.position.x;z=walkTarget.z-marker.position.z;if(Math.hypot(x,z)<.1)walkTarget=null;}if(x||z){let norm=Math.hypot(x,z),dx=x/norm*delta*(activeCity==='lagos'?2.2:5.8),dz=z/norm*delta*(activeCity==='lagos'?2.2:5.8);if(isLand(marker.position.x+dx,marker.position.z+dz)){marker.position.x+=dx;marker.position.z+=dz;marker.rotation.y=Math.atan2(dx,dz);camera.position.x+=dx;camera.position.z+=dz;controls.target.x+=dx;controls.target.z+=dz;}else walkTarget=null;}}
 controls.update();camera.updateMatrixWorld();const occupied=[];
 for(const label of labels){projection.copy(label.point).project(camera);const x=(projection.x+1)*innerWidth/2,y=(-projection.y+1)*innerHeight/2,width=label.button.offsetWidth||label.place.name.length*7+36;let visible=label.place.city===activeCity&&showNames&&projection.z<1&&projection.z>-1&&x>width/2+8&&x<innerWidth-width/2-8&&y>(mobile()?210:225)&&y<innerHeight-100;if(visible&&x>innerWidth-78&&Math.abs(y-innerHeight/2)<100)visible=false;if(visible&&label.place!==selected){if(occupied.some(p=>Math.abs(p.x-x)<(p.w+width)/2+3&&Math.abs(p.y-y)<29))visible=false;else occupied.push({x,y,w:width});}label.button.hidden=!visible;if(visible)label.button.style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;}
 for(let i=0;i<traffic.length;i++)traffic[i].position.x=((time*.001*(i%2?-1:1)+i*6)%30+30)%30-15;
 renderer.render(scene,camera);requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
await Promise.all(tasks);$('loader').hidden=true;host.dataset.ready='true';
const initialCity=new URLSearchParams(location.search).get('city');if(['abuja','dublin'].includes(initialCity))switchCity(initialCity);
if(document.modelContext?.registerTool){const context=document.modelContext;for(const tool of [{name:'switch_map_city',description:'Switch between the Lagos, Abuja and Dublin map views.',inputSchema:{type:'object',properties:{city:{type:'string',enum:['lagos','abuja','dublin']}},required:['city'],additionalProperties:false},execute:input=>switchCity(input?.city)},{name:'list_map_places',description:'List the landmarks in the Lagos, Abuja and Dublin maps.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>data.map(({id,name,city,x,z})=>({id,name,city,x,z}))},{name:'focus_map_place',description:'Select and focus a landmark in the map.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:input=>{const p=data.find(p=>p.id===input?.id);if(!p)throw new Error('Unknown map place');selectPlace(p);flyTo(p.x,p.z,10);return {id:p.id,name:p.name,selected:true};}}]){try{await context.registerTool(tool)}catch(e){console.warn('Map tool unavailable',e)}}}
