import * as THREE from 'three';
import {MapControls} from 'three/addons/controls/MapControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {buildAbuja} from './abuja.js';
import {buildDublin,DUBLIN_BACKGROUND} from './dublin.js';
import {buildDublinMotion} from './dublin-motion.js';
import {buildDublinPort} from './dublin-port.js';
import {buildDublinSecondHarbour} from './dublin-second-harbour.js';
import {buildDublinBridges,DUBLIN_DRAWBRIDGE_XS} from './dublin-bridges.js';
import {buildReferenceTreeInstances} from './reference-props.js';
import {MAP_WORLD_BOUNDS,fitOverview,normalizeCameraView,clampCameraToBounds,cameraClipPlanes} from './map-camera.js';
import {bridgeSpanAt as findBridgeSpanAt,mayEnterBridge} from './walk-boundaries.js';
import {DUBLIN_ROAD_NETWORK,DUBLIN_ROAD_LANES,roadSurfaceY as dublinRoadSurfaceY} from './dublin-road-network.js';
import {measureRoadConnectivity} from './road-connectivity.js';

let runtimeSequence=0;

export async function mountMap({scene,camera,renderer,modelLoader,onState=()=>{},initialState={},signal}={}) {
 if(!scene||!camera||!renderer) throw new TypeError('mountMap requires the R3F scene, camera, and renderer');
 const host=document.getElementById('map'), canvas=renderer.domElement, instanceId=String(++runtimeSequence);
 if(!host) throw new Error('Map shell is missing #map');
 const $=id=>{const node=document.getElementById(id);if(!node)throw new Error(`Map shell is missing #${id}`);return node};
 const viewport=()=>{const rect=host.getBoundingClientRect();return {width:rect.width||innerWidth,height:rect.height||innerHeight}};
 const {width:initialWidth,height:initialHeight}=viewport();
 if(camera.isPerspectiveCamera){camera.aspect=initialWidth/initialHeight;camera.updateProjectionMatrix()}
 const cleanups=[], labelNodes=[], runtimeRoots=[], ownedGeometries=new Set(), ownedMaterials=new Set(), ownedTextures=new Set();
 let dublinSceneObjectNames=[];
 let alive=true, cityReady=false, applyingState=false;
 const listen=(target,event,handler,options)=>{target.addEventListener(event,handler,options);cleanups.push(()=>target.removeEventListener(event,handler,options));};
 const setHandler=(node,key,handler)=>{const prior=node[key];node[key]=handler;cleanups.push(()=>{if(node[key]===handler)node[key]=prior})};
 const disposeNode=(root)=>{root.traverse?.(node=>{if(node.userData?.referenceInstance)node.dispose?.();if(node.userData?.mapModelAsset)return;if(node.geometry)ownedGeometries.add(node.geometry);if(Array.isArray(node.material))node.material.forEach(m=>ownedMaterials.add(m));else if(node.material)ownedMaterials.add(node.material);});};
 const dimensions=viewport;let lastCameraViews=initialState.cameraViews, appliedDistrict=initialState.district||'all';
 const controller=new AbortController();
 const abort=()=>controller.abort();
 if(signal){if(signal.aborted)abort();else signal.addEventListener('abort',abort,{once:true});cleanups.push(()=>signal.removeEventListener('abort',abort))}
 const assertAlive=()=>{if(!alive||controller.signal.aborted)throw new DOMException('Map mount cancelled','AbortError')};
 const defaultLoader=new GLTFLoader();
 const data=await fetch('/places.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error(`Map data could not load (${r.status})`);return r.json()});assertAlive();
 const loadModel=modelLoader||((path)=>defaultLoader.loadAsync(`/assets/${path}.glb`).then(result=>result.scene));
 const previousClearColor=renderer.getClearColor?.(new THREE.Color()).clone();
 const previousClearAlpha=renderer.getClearAlpha?.();
 const previousRendererState={toneMapping:renderer.toneMapping,toneMappingExposure:renderer.toneMappingExposure,shadowEnabled:renderer.shadowMap.enabled,shadowType:renderer.shadowMap.type};
 const previousCanvasState={ariaLabel:canvas.getAttribute('aria-label'),tabIndex:canvas.getAttribute('tabindex')};
 const previousHostState={city:host.dataset.city,ariaLabel:host.getAttribute('aria-label')};
 renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.setClearColor('#67afd5');
 canvas.setAttribute('aria-label','3D city map. Drag to pan, scroll to zoom.');canvas.tabIndex=0;
 const publish=(extra={})=>{if(applyingState)return;clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes();const cameraViews={...cityCameras,[activeCity]:{position:camera.position.toArray(),target:controls.target.toArray()}};onState({city:activeCity,names:showNames,homes:showHomes,boards:showBoards,walking,selectedId:selected?.id||null,selectedPlace:selected?{id:selected.id,name:selected.name,city:selected.city,x:selected.x,z:selected.z,area:selected.area||null,kind:selected.kind||null,sourceUrl:selected.sourceUrl||null,emoji:selected.emoji||emoji?.[selected.id]||'🏠',description:selected.description||descriptions?.[selected.id]||(selected.city==='abuja'?`${selected.name} in ${selected.area}. Explore the landmark and its surroundings on the Abuja map.`:`${selected.name} on the ${district(selected)} side of the city.`),district:selected.city!=='lagos'?selected.area:selected.z< -2?'Mainland':selected.x>8?'Lekki':'Island'}:null,cameraViews,ready:cityReady,progress:tasks.length?`Building the city · ${Math.round(settled/tasks.length*100)}%`:'Building the city',loadPercent:tasks.length?Math.round(settled/tasks.length*100):0,...extra})};

const controls=new MapControls(camera,canvas);
controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=7;controls.maxDistance=170;
controls.maxPolarAngle=Math.PI*.44;controls.minPolarAngle=.18;controls.minAzimuthAngle=-Math.PI/3;controls.maxAzimuthAngle=Math.PI/3;controls.screenSpacePanning=false;
camera.position.set(0,40,40);controls.target.set(0,0,0);
const hemisphere=new THREE.HemisphereLight('#eaf4ff','#c9b99a',.9);scene.add(hemisphere);runtimeRoots.push(hemisphere);
const sun=new THREE.DirectionalLight('#ffffff',1.6);sun.position.set(32,56,24);sun.castShadow=true;
sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-50,right:50,top:50,bottom:-50,near:1,far:120});
 sun.shadow.normalBias=.02;sun.shadow.bias=-.00008;scene.add(sun);runtimeRoots.push(sun);
const materials=new Map(), modelCache=new Map();
const world=new THREE.Group(), estate=new THREE.Group(), boards=new THREE.Group();scene.add(world,estate,boards);runtimeRoots.push(world,estate,boards);
const mat=color=>{if(!materials.has(color)){const material=new THREE.MeshStandardMaterial({color,roughness:.95});materials.set(color,material);ownedMaterials.add(material)}return materials.get(color)};
function box(parent,x,y,z,w,h,d,color){const geometry=new THREE.BoxGeometry(w,h,d);ownedGeometries.add(geometry);const mesh=new THREE.Mesh(geometry,mat(color));mesh.position.set(x,y,z);mesh.castShadow=h>.15;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function cylinder(parent,x,y,z,r,h,color,r2=r,segments=12){const geometry=new THREE.CylinderGeometry(r,r2,h,segments);ownedGeometries.add(geometry);const mesh=new THREE.Mesh(geometry,mat(color));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function dome(parent,x,y,z,r,color){const geometry=new THREE.SphereGeometry(r,20,10,0,Math.PI*2,0,Math.PI/2);ownedGeometries.add(geometry);const m=new THREE.Mesh(geometry,mat(color));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
function textSurface(text,color,w,parent,x,y,z,flat=true,bg=null){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=flat?128:384;const ctx=canvas.getContext('2d');if(bg){ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';let size=flat?90:94;do{ctx.font=`800 ${size}px Arial`;size-=2}while(ctx.measureText(text).width>950&&size>16);ctx.fillText(text,512,canvas.height/2);const texture=new THREE.CanvasTexture(canvas);ownedTextures.add(texture);texture.colorSpace=THREE.SRGBColorSpace;const geometry=new THREE.PlaneGeometry(w,w*canvas.height/1024),material=new THREE.MeshBasicMaterial({map:texture,transparent:!bg,depthWrite:!!bg,side:THREE.DoubleSide});ownedGeometries.add(geometry);ownedMaterials.add(material);const mesh=new THREE.Mesh(geometry,material);if(flat)mesh.rotation.x=-Math.PI/2;mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
function road(x,z,w,d){box(world,x,.211,z,w,.023,d,'#969c9f');}
// The coast, lot coordinates, and road network follow the reference map.
box(world,25,-.16,-20,250,.1,230,'#67afd5');
[[0,-11.4,42,18,'#a7cc86'],[-4.275,7.65,25.05,13.5,'#c7e0a5'],[15,7.5,12.9,13.8,'#c7e0a5'],[5.1,-.75,2.7,2.5,'#c7e0a5'],[6,15.3,34.5,2.7,'#ecd9a6'],[8.25,18.525,33.9,3.6,'#d9dccf'],[-23.85,-11.4,6,18,'#a7cc86']].forEach(([x,z,w,d,c])=>box(world,x,.05,z,w,.3,d,c));
textSurface('MAINLAND','#759a58',8,world,-12,.217,-17.4);
textSurface('ISLAND','#93ad73',6,world,-9,.217,1.5);
textSurface('LAGOS LAGOON','#d0e8f2',8,world,11.4,.01,-.9);
textSurface('ATLANTIC OCEAN','#c3e2ef',12,world,23,.01,23);
textSurface('EKO ATLANTIC','#82917e',7,world,11,.217,18.7);
[[0,-4.5,33,.5],[-1.2,2.175,.5,2.55],[-4.575,2.4,22.65,.5],[12.75,6,8.7,.5],[8.25,19.575,33,.42],[-23.1,-11.4,.45,17.4]].forEach(args=>road(...args));
function bridge(x,z,length,across=false,cable=false){const g=new THREE.Group();g.position.set(x,0,z);if(across)g.rotation.y=Math.PI/2;world.add(g);box(g,0,.29,0,.52,.13,length,'#a1a7ab');for(const side of [-1,1]){box(g,side*.3,.43,0,.045,.13,length,'#c5c8ca');for(let i=-length/2+.25;i<length/2;i+=.6)cylinder(g,side*.22,-.15,i,.04,.8,'#999e9c');}if(cable){for(let z of [-length*.3,length*.3]){box(g,0,1.5,z,.08,2.5,.08,'#eee6d6');for(let k of [-1,1]){const p=[new THREE.Vector3(0,2.6,z),new THREE.Vector3(0,.4,z+k*length*.35)];g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),new THREE.LineBasicMaterial({color:'#e2dfd2'})));}}}return g;}
bridge(-1.2,-.75,3.3);bridge(7.95,6,1.2,true,true);
const modelPaths=async path=>{if(!modelCache.has(path))modelCache.set(path,Promise.resolve().then(()=>loadModel(path)));return modelCache.get(path)};
async function addModel(parent,path,height,pos=[0,0,0],tint=null,rotation=0){const original=await modelPaths(path);assertAlive();const object=original.clone(true);object.traverse(n=>{n.userData.mapModelAsset=true});object.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;if(tint){n.material=n.material.clone();ownedMaterials.add(n.material);n.material.color.set(tint)}}});const bounds=new THREE.Box3().setFromObject(object),center=bounds.getCenter(new THREE.Vector3()),factor=height/(bounds.getSize(new THREE.Vector3()).y||1);object.position.set(-center.x,-bounds.min.y,-center.z);const group=new THREE.Group();group.add(object);group.scale.setScalar(factor);group.position.set(...pos);group.rotation.y=rotation;parent.add(group);return group;}
data.push({id:'airport',name:'Airport',x:-35,z:-12,w:21,d:19,h:2,models:[]},{id:'refinery',name:'Refinery',x:-25,z:8,w:13,d:13,h:2.6,models:[]});
const emoji={shrine:'🎷',viewingCentre:'⚽',mamaPut:'🍲',yabaHub:'💡',balogun:'🧺',freedomPark:'🎭',ikoyiGym:'🏋️',office:'🏢',clubEko:'🪩',lcc:'🌉',mall:'🛍️',library:'📚',elegushi:'🏖️',hospital:'🏥',salon:'💇🏾‍♀️',rooftop:'🕯️',policeStation:'🚓',church:'⛪',mosque:'🕌',naijaRadio:'📻',pollingUnit:'🗳️',ekoHotel:'🏨',polanco:'🚘',boatCruise:'⛵',golfClub:'⛳',courthouse:'⚖️',unilag:'🎓',casino:'🎰',mindSpace:'🫶🏾',stadium:'🏟️',ojuelegba:'🎱'};
const descriptions={shrine:'Music and nightlife on the Mainland.',yabaHub:'The technology hub in Yaba.',balogun:'Colourful market stalls on Lagos Island.',lcc:'Forest trails and an elevated canopy walkway.',elegushi:'The sandy shoreline on the Atlantic.',unilag:'University buildings, gardens, and sports courts.',freedomPark:'Gardens and paths in the heart of the Island.',golfClub:'A green course beside the Lekki–Ikoyi Link.',boatCruise:'The dock on Lagos Lagoon.',ekoHotel:'The hotel grounds on Lagos Island.',stadium:'A football stadium on the Mainland.'};
let selected=null,showNames=initialState.names??true,showHomes=initialState.homes??true,showBoards=initialState.boards??true,walking=false,transition=null,activeCity='lagos';
data.forEach(p=>p.city='lagos');host.dataset.city=activeCity;
const labels=[], tasks=[], taskErrors=[];let settled=0;
function measureLabel(label){const {button}=label,wasHidden=button.hidden,priorVisibility=button.style.visibility,priorTransform=button.style.transform;button.hidden=false;button.style.visibility='hidden';button.style.transform='translate(-10000px,-10000px)';label.width=button.getBoundingClientRect().width||label.width||label.place.name.length*7+36;button.style.transform=priorTransform||'translate(-50%,-100%)';button.style.visibility=priorVisibility;button.hidden=wasHidden;return label.width}
function task(p){tasks.push(Promise.resolve(p).catch(error=>{if(error?.name!=='AbortError')taskErrors.push(error);throw error}).finally(()=>{settled++;if(alive){$('progress').textContent=`Building the city · ${Math.round(settled/tasks.length*100)}%`;$('loadbar').style.width=`${settled/tasks.length*100}%`;publish();}}));}
function sign(parent,text,x,y,z,w=1.2){textSurface(text,'#ffffff',w,parent,x,y,z,false,'#008751')}
function garden(g,w,d){box(g,0,.008,0,w,.025,d,'#8aba65');box(g,0,.025,0,.12,.02,d,'#d5ccaa');box(g,0,.025,0,w,.02,.12,'#d5ccaa');}
function special(p,g){const id=p.id;
 if(id==='airport'){box(g,0,-.015,0,21,.05,19,'#afb59d');box(g,0,.03,-6,20,.04,2.3,'#50595c');for(let i=-9;i<10;i+=1.2)box(g,i,.055,-6,.6,.015,.07,'#ecebd8');box(g,0,.03,-2,20,.04,1.2,'#95998e');box(g,0,.6,3,9,1.2,3,'#dce2dc');box(g,0,1.23,3,9.3,.08,3.2,'#838f94');box(g,0,.6,4.51,8,.6,.025,'#73a1b4');cylinder(g,-6,1.3,3,.22,2.6,'#dce0dd');box(g,-6,2.7,3,.8,.5,.7,'#6e9eae');for(let i=0;i<4;i++){const plane=new THREE.Group();plane.position.set(-6+i*4,.5,.1);g.add(plane);const fuselage=cylinder(plane,0,0,0,.13,2,'#f0f0e7',.08);fuselage.rotation.x=Math.PI/2;box(plane,0,0,0,1.9,.045,.4,'#e9ebe3');box(plane,0,.09,.7,.05,.35,.4,'#97afb8');box(plane,0,0,.7,.7,.04,.2,'#e5e9e0');}sign(g,'LAGOS AIRPORT',0,1,4.54,3);}
 if(id==='refinery'){box(g,0,-.015,0,13,.05,13,'#c9c6b7');for(let i=0;i<5;i++){const x=-4.6+i*2.25;cylinder(g,x,.8,-3,.9,1.6,'#d7d7ce');dome(g,x,1.6,-3,.9,'#c6c9c3');cylinder(g,x,.5,0,.85,1,'#bfc4bf');}for(let i=0;i<3;i++){cylinder(g,-4+i*2.2,1.8,3,.35,3.6,'#c7c9c1');for(let y=.5;y<3.6;y+=.55)cylinder(g,-4+i*2.2,y,3,.41,.05,'#dfc05c');}box(g,3,.7,3,3,1.4,2.3,'#969b93');for(let i=0;i<2;i++)cylinder(g,2.5+i,2.3,3,.17,3.5,'#c1c4ba');for(let i=0;i<5;i++)box(g,-4+i*2.1,.4,4.9,1.8,.09,.09,'#9d8d57');sign(g,'REFINERY',0,.8,5.9,2.6);}
 if(id==='mosque'){box(g,0,.35,0,1.1,.7,1,'#f4efe6');dome(g,0,.7,0,.38,'#059669');cylinder(g,.62,.65,.4,.09,1.3,'#f4efe6',.11);dome(g,.62,1.3,.4,.11,'#059669');}
 if(id==='courthouse'){box(g,0,.04,0,1.5,.08,1.15,'#d6d3cc');box(g,0,.43,-.12,1.3,.7,.8,'#f4efe6');for(let x=-.5;x<=.5;x+=.25)cylinder(g,x,.39,.4,.045,.62,'#f8fafc');box(g,0,.74,.02,1.42,.08,.98,'#e7e0d2');const roof=new THREE.Mesh(new THREE.ConeGeometry(.86,.32,4),mat('#7c2d12'));roof.position.set(0,.94,.02);roof.rotation.y=Math.PI/4;g.add(roof);sign(g,'HIGH COURT',0,.74,.52);}
 if(id==='church'){box(g,0,1.35,0,.06,.42,.06,'#e3be60');box(g,0,1.42,0,.24,.06,.06,'#e3be60');}
 if(id==='hospital'){box(g,0,1.62,0,.5,.12,.14,'#e5484d');box(g,0,1.62,0,.14,.12,.5,'#e5484d');}
 if(id==='library'||id==='mindSpace'||id==='naijaRadio'||id==='casino'){const library=id==='library',casino=id==='casino';box(g,0,library?.55:.4,-.1,1.2,library?1.1:.8,1,library?'#6d5a9c':casino?'#2a1838':'#e8f3ec');box(g,0,library?1.13:.83,-.1,1.28,.06,1.08,library?'#b9a8e6':'#52b788');box(g,0,.3,.41,.95,.26,.02,'#bde0fe');sign(g,p.name.toUpperCase(),0,.65,.43);if(casino)dome(g,0,.85,-.1,.36,'#c9a227');if(id==='naijaRadio'){cylinder(g,.85,1.3,0,.025,2.6,'#a4a9ae');for(let i=0;i<3;i++)box(g,.85,1.5+i*.4,0,.45,.025,.03,'#b9c0c5');}}
 if(id==='pollingUnit'){for(const x of [-.55,.55])for(const z of [-.4,.4])cylinder(g,x,.32,z,.02,.64,'#cbd5e1');[-.45,-.15,.15,.45].forEach((x,i)=>box(g,x,.68,0,.3,.06,.95,i%2?'#ffffff':'#008751'));box(g,0,.22,0,.8,.04,.4,'#8b6a4a');sign(g,'POLLING UNIT',0,.5,.52);}
 if(id==='mall'){box(g,0,.53,0,2.5,1.05,1.5,'#f4efe6');box(g,0,1.08,0,2.7,.12,1.7,'#e0e3df');for(const x of [-.75,0,.75])box(g,x,.35,.76,.45,.7,.03,'#273c4c');sign(g,'THE PALMS',0,.88,.8,1.7);}
 if(id==='balogun'){const colors=['#efb23b','#279ea1','#535ac0','#d83f58','#54a861'];for(let x=0;x<5;x++)for(let z=0;z<3;z++){box(g,(x-2)*.76,.4,z*.76-.4,.7,.07,.72,colors[(x+z)%5]);box(g,(x-2)*.76,.17,z*.76-.4,.65,.32,.64,'#b59768');}}
 if(id==='freedomPark'||id==='golfClub'||id==='ekoHotel'){garden(g,p.w,p.d);if(id==='ekoHotel'){box(g,-.8,.032,.7,1.3,.025,.75,'#52bcd5');for(let i=0;i<4;i++)task(addModel(g,'commercial/detail-parasol-a',.35,[-1.4+i*.7,0,1.35]));}if(id==='golfClub'){box(g,.55,.03,0,.75,.02,.45,'#69bdd7');for(const x of [-1,1]){cylinder(g,x,.42,-1.2,.01,.8,'#f3f1e1');box(g,x+.09,.76,-1.2,.18,.13,.02,'#e24646');}}}
 if(id==='unilag'){garden(g,p.w,p.d);box(g,1.8,.03,1.2,2.5,.02,1.5,'#bc5e3c');box(g,1.8,.047,1.2,2,.015,1,'#7ead62');box(g,-.8,.03,1.25,2,.02,1.4,'#688f55');for(let i=0;i<6;i++)task(addModel(g,'suburban/tree-small',.65,[-3+i*1.15,0,2.1]));}
 if(id==='lcc'){box(g,0,.012,0,6.7,.035,3.8,'#81ab60');for(let i=0;i<27;i++){let x=(Math.sin(i*127.1)*.5+.5)*5.8-2.9,z=(Math.cos(i*61.3)*.5+.5)*3.3-1.65;task(addModel(g,i%3?'suburban/tree-small':'suburban/tree-large',1+((i*7)%9)*.08,[x,0,z]));}for(let i=0;i<3;i++){let b=box(g,-1.9+i*1.5,.95,-.5+i*.55,1.7,.045,.25,'#aa8b5a');b.rotation.y=-.35;for(let x of [-2.6+i*1.5,-1.2+i*1.5])cylinder(g,x,.58,-.5+i*.55,.025,1.12,'#9a7c49');}sign(g,'CANOPY WALK',-2.5,.27,1.7,1.5);}
 if(id==='elegushi'){for(let i=0;i<9;i++)task(addModel(g,`commercial/detail-parasol-${i%2?'a':'b'}`,.55,[-2.6+i*.65,0,.45]));sign(g,'ELEGUSHI',-1.5,.28,-.35);}
 if(id==='stadium'){box(g,0,.02,0,2.4,.04,1.4,'#3f8f3a');box(g,0,.05,0,.025,.008,1.4,'#fff');const ring=new THREE.Mesh(new THREE.CylinderGeometry(1.55,1.2,.45,40,1,true),new THREE.MeshStandardMaterial({color:'#c6d9ca',side:THREE.DoubleSide}));ring.scale.z=.7;ring.position.y=.27;g.add(ring);for(let x of [-1.65,1.65])for(let z of [-.95,.95]){cylinder(g,x,.7,z,.022,1.4,'#a4a9ae');box(g,x,1.4,z,.32,.13,.08,'#fffae5');}sign(g,'STADIUM',0,.33,1.14);}
 if(id==='boatCruise'){task(addModel(g,'pirate/boat-row-small',.35,[.4,.03,.4]));}
}
for(const place of data){if(place.id.startsWith('home_')&&place.id!=='home_yaba')continue;const g=new THREE.Group();g.position.set(place.x,.205,place.z);world.add(g);place.group=g;box(g,0,-.012,0,place.w,.03,place.d,'#e4e5d6');special(place,g);for(const model of place.models)task(addModel(g,model.model,model.height,model.position,model.tint));const button=document.createElement('button');labelNodes.push(button);button.className='label';button.innerHTML=`<span>${emoji[place.id]||(place.id==='airport'?'✈️':place.id==='refinery'?'🛢️':'🏠')}</span>${place.name}`;button.setAttribute('aria-label',`Select ${place.name}`);setHandler(button,'onclick',()=>selectPlace(place));$('labels').appendChild(button);labels.push({place,button,point:new THREE.Vector3(place.x,.205+place.h,place.z)});}
const abuja=buildAbuja({box,textSurface});scene.add(abuja.world);runtimeRoots.push(abuja.world,abuja.homes,abuja.boards);data.push(...abuja.places);abuja.world.visible=false;abuja.homes.visible=showHomes;abuja.boards.visible=showBoards;
const dublin=buildDublin({textSurface});scene.add(dublin.world);runtimeRoots.push(dublin.world,dublin.homes,dublin.boards);data.push(...dublin.places);dublin.world.visible=false;dublin.homes.visible=showHomes;dublin.boards.visible=showBoards;
const dublinPort=buildDublinPort({textSurface});dublin.world.add(dublinPort.world);dublin.places.push(...dublinPort.places);data.push(...dublinPort.places);
const dublinSecondHarbour=buildDublinSecondHarbour({textSurface});dublin.world.add(dublinSecondHarbour.world);dublin.places.push(...(dublinSecondHarbour.places||[]));data.push(...(dublinSecondHarbour.places||[]));
const dublinBridges=buildDublinBridges({textSurface});dublin.world.add(dublinBridges.world);
const dublinMotion=buildDublinMotion();dublin.world.add(dublinMotion.group);estate.visible=showHomes;boards.visible=showBoards;
// These are the same local GLBs used by the source-backed Lagos scene.
task(Promise.all(['sedan','suv','taxi','van'].map(async kind=>[kind,await modelPaths(`car/${kind}`)])).then(entries=>{assertAlive();dublinMotion.setVehicleModels(Object.fromEntries(entries));}));
task(Promise.all([modelPaths('suburban/tree-large'),modelPaths('suburban/tree-small')]).then(([large,small])=>{assertAlive();if(dublin.treePlacements?.length){const trees=buildReferenceTreeInstances(dublin.treePlacements,{large,small});dublin.world.add(trees);}}));
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');let dublinElapsed=0,dublinSimulationTime=0,motionPausedForVerification=false;
function roadVehicleSnapshot(){
 const state=dublinMotion.getSnapshot?.()||dublinMotion.snapshot?.(dublinSimulationTime)||{};
 const vehicles=Array.isArray(state.roadVehiclePositions)?[...state.roadVehiclePositions]:(state.actors||[]).filter(actor=>actor.kind==='car').map(actor=>({id:actor.id,x:actor.position.x,z:actor.position.z,length:.65}));
 if(walking&&isOnBridgeDeck(marker.position.x,marker.position.z))vehicles.push({id:'map-walker',x:marker.position.x,z:marker.position.z,length:.45,onBridge:true});
 return vehicles;
}
function bridgeSpanAt(x,z,padding=.22){return findBridgeSpanAt(x,z,DUBLIN_DRAWBRIDGE_XS,padding)}
function isOnHowthApproach(x,z){
 if(!Number.isFinite(x)||!Number.isFinite(z))return false;
 return DUBLIN_ROAD_LANES.some(lane=>lane.routeId==='howth-coastal-approach'&&lane.segments.some(segment=>{
  const dx=segment.b.x-segment.a.x,dz=segment.b.z-segment.a.z,length=dx*dx+dz*dz;
  const t=length?Math.max(0,Math.min(1,((x-segment.a.x)*dx+(z-segment.a.z)*dz)/length)):0;
  return (x-segment.a.x-t*dx)**2+(z-segment.a.z-t*dz)**2<=(segment.width/2+.08)**2;
 }));
}
function isOnBridgeDeck(x,z){return bridgeSpanAt(x,z)!==undefined}
function resetDublinSimulation(){
 if(dublinPort.resetTimeline)dublinPort.resetTimeline();else{dublinPort.dispatch('reset');dublinPort.update(0,{bridges:dublinBridges})}dublinBridges.reset();dublinMotion.update(0,{bridges:dublinBridges});dublinSecondHarbour.update(0);dublinElapsed=0;dublinSimulationTime=0;
}
function advanceDublinSimulation(targetSeconds,fullSnapshot=true){
 if(!Number.isFinite(targetSeconds)||targetSeconds<0)throw new TypeError('Elapsed seconds must be nonnegative');
 if(targetSeconds+1e-9<dublinSimulationTime)resetDublinSimulation();
 if(dublinPort.snapshot().paused)return fullSnapshot?snapshot():simulationSnapshot();
 while(dublinSimulationTime+1e-9<targetSeconds){
  const next=Math.min(targetSeconds,dublinSimulationTime+.05);
  dublinPort.update(next,{bridges:dublinBridges});
  dublinMotion.update(next,{bridges:dublinBridges});
  dublinSecondHarbour.update(next);
  dublinBridges.update(next,{ships:dublinPort.snapshot().vessels,vehicles:roadVehicleSnapshot()});
  // Reconcile permissions against the same timestamp so new gate state is visible
  // before a renderer frame can move a ship or car through the span.
  dublinPort.update(next,{bridges:dublinBridges});
  dublinMotion.update(next,{bridges:dublinBridges});
  dublinBridges.update(next,{ships:dublinPort.snapshot().vessels,vehicles:roadVehicleSnapshot()});
  dublinSimulationTime=next;
 }
 return fullSnapshot?snapshot():simulationSnapshot();
}
function seekDublinSimulation(seconds){
 if(!Number.isFinite(seconds)||seconds<0)throw new TypeError('Elapsed seconds must be nonnegative');
 if(dublinPort.snapshot().paused&&seconds>=dublinSimulationTime)return simulationSnapshot();
 if(seconds<dublinSimulationTime)resetDublinSimulation();
 dublinElapsed=seconds;return advanceDublinSimulation(seconds,false);
}
const airportRotors=(dublin.airport?.userData.helicopters||[]).flatMap(helicopter=>helicopter.userData.rotors||[]);
for(const place of [...abuja.places,...dublin.places]){const button=document.createElement('button');labelNodes.push(button);button.className='label';button.innerHTML=`<span>${place.emoji}</span>${place.name}`;button.setAttribute('aria-label',`Select ${place.name}`);setHandler(button,'onclick',()=>selectPlace(place));$('labels').appendChild(button);const offset=place.tag||[0,place.h,0],label={place,button,point:new THREE.Vector3(place.x+offset[0],.28+offset[1],place.z+offset[2]),width:0};button.hidden=true;measureLabel(label);labels.push(label);}
const labelPriority={dubPort:111,dubHapenny:110,dubTrinity:109,dubSpire:108,dubAirport:107,dubGreen:106,dubGuinness:105,dubBeckett:104,dubTemple:103,abjAssembly:100,abjAsoRock:99,abjAirport:98,abjJabiLake:97,abjZumaRock:96,abjMosque:95,abjMillenniumPark:90};labels.sort((a,b)=>(labelPriority[b.place.id]||0)-(labelPriority[a.place.id]||0));
// Repeated housing plots are visual map scenery, without player data.
box(estate,0,.055,-25,42,.3,7.5,'#add08f');box(estate,19,.055,9.4,8,.3,12,'#c7e0a5');
for(let row=0;row<4;row++)for(let col=0;col<22;col++){const x=-20+col*1.85,z=-27.8+row*1.75;box(estate,x,.219,z,1.4,.03,1.4,'#e4e6d8');task(addModel(estate,'suburban/building-type-c',.62,[x,.24,z]));}
for(let row=0;row<7;row++)for(let col=0;col<4;col++){const x=16.25+col*1.65,z=4.4+row*1.65;box(estate,x,.219,z,1.4,.03,1.4,'#e6e7dc');task(addModel(estate,'suburban/building-type-t',.64,[x,.24,z]));}
for(const [i,x,z] of [[0,-15,-15],[1,-16,-7],[2,-8,-3.5],[3,1,-3.8],[4,14,-4],[5,-3,.1],[6,16,1],[7,12,7.5],[8,-8,10.5],[9,2,14.4],[10,18,13.8]]){box(boards,x,1.55,z,3.3,1.7,.11,'#202431');for(const dx of [-1.3,1.3])box(boards,x+dx,.75,z,.09,1.5,.09,'#202431');textSurface(i%2?'LAGOS LIFE':'YOUR AD HERE','#fff',3.13,boards,x,1.55,z+.067,false,i%2?'#206b57':'#276998');}
for(let i=0;i<28;i++){const x=-17+((i*13)%38),z=i%2?-4.9:14.3;task(addModel(world,'pirate/palm-straight',1.1,[x,.205,z]));}
const traffic=[];for(let i=0;i<5;i++){const group=new THREE.Group();world.add(group);group.position.set(-15+i*7,.24,-4.5);task(addModel(group,i%2?'car/sedan':'car/van',.26,[0,0,0],i%2?null:'#f3c43d',Math.PI/2));traffic.push(group);}
const marker=new THREE.Group();marker.visible=false;scene.add(marker);runtimeRoots.push(marker);cylinder(marker,0,.04,0,.2,.06,'#54af7d');cylinder(marker,0,.6,0,.13,.55,'#252e43');dome(marker,0,.92,0,.14,'#a77750');box(marker,-.1,.23,0,.065,.4,.09,'#252e43');box(marker,.1,.23,0,.065,.4,.09,'#252e43');
marker.position.set(.75,.22,-6);let walkTarget=null,keys=new Set(),lastTime=0;
const selectionGeometry=new THREE.RingGeometry(.95,1.03,48),selectionMaterial=new THREE.MeshBasicMaterial({color:'#408b61',side:THREE.DoubleSide,transparent:true,opacity:.75});ownedGeometries.add(selectionGeometry);ownedMaterials.add(selectionMaterial);const selectionRing=new THREE.Mesh(selectionGeometry,selectionMaterial);selectionRing.rotation.x=-Math.PI/2;selectionRing.visible=false;scene.add(selectionRing);runtimeRoots.push(selectionRing);
const overviewBounds={
 lagos:{...MAP_WORLD_BOUNDS.lagos,maxY:12},
 abuja:{...MAP_WORLD_BOUNDS.abuja,maxY:20},
 dublin:{...MAP_WORLD_BOUNDS.dublin,maxY:20},
};
const cityViews={};
const refreshCityViews=()=>{for(const city of ['lagos','abuja','dublin']){const view=fitOverview(overviewBounds[city],camera.aspect, camera.fov,{safeHeight:city==='lagos'?.72:.62,margin:1.16,targetY:overviewBounds[city].maxY/2});cityViews[city]={position:view.position,target:view.target};}};
refreshCityViews();
const cityCameras={};
for(const city of ['lagos','abuja','dublin'])if(initialState.cameraViews?.[city])cityCameras[city]=initialState.cameraViews[city];
const cameraLimits={lagos:{min:7,max:320},abuja:{min:12,max:800},dublin:{min:12,max:1200}};
const updateOverviewLimits=()=>{for(const city of ['lagos','abuja','dublin'])cameraLimits[city].max=Math.max(90,cityViews[city].position.distanceTo(cityViews[city].target)*1.4)};
updateOverviewLimits();
controls.minDistance=cameraLimits[activeCity].min;controls.maxDistance=cameraLimits[activeCity].max;
const sceneMaxY={lagos:12,abuja:20,dublin:24};
const sceneClipBounds={...MAP_WORLD_BOUNDS,lagos:{...MAP_WORLD_BOUNDS.lagos,minX:-100,maxX:150,minZ:-135,maxZ:95}};
function updateCameraClipPlanes(){if(!camera.isPerspectiveCamera)return;const distance=camera.position.distanceTo(controls.target),planes=cameraClipPlanes(distance,controls.target,MAP_WORLD_BOUNDS[activeCity],sceneMaxY[activeCity],sceneClipBounds[activeCity]);if(Math.abs(camera.near-planes.near)>.005||Math.abs(camera.far-planes.far)>.5){camera.near=planes.near;camera.far=planes.far;camera.updateProjectionMatrix()}}
function settleCameraControls(){const damping=controls.enableDamping;controls.enableDamping=false;controls.update();controls.enableDamping=damping;clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes()}
listen(controls,'change',()=>{clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes()});
updateCameraClipPlanes();
const cityNames={lagos:'🇳🇬 Lagos',abuja:'🇳🇬 Abuja',dublin:'🇮🇪 Dublin'};
function switchCity(city){
 if(!['lagos','abuja','dublin'].includes(city))throw new Error('Unknown map city');
 if(city===activeCity)return {city,changed:false};
 settleCameraControls();cityCameras[activeCity]={position:camera.position.toArray(),target:controls.target.toArray()};
 walking=false;marker.visible=false;walkTarget=null;keys.clear();controls.enableRotate=true;transition=null;clearSelection();
 $('walk').setAttribute('aria-pressed','false');$('walk-controls').hidden=true;$('hint').hidden=false;
 activeCity=city;world.visible=city==='lagos';estate.visible=city==='lagos'&&showHomes;boards.visible=city==='lagos'&&showBoards;abuja.world.visible=city==='abuja';abuja.homes.visible=showHomes;abuja.boards.visible=showBoards;dublin.world.visible=city==='dublin';dublin.homes.visible=showHomes;dublin.boards.visible=showBoards;
 renderer.setClearColor(city==='abuja'?'#93b56c':city==='dublin'?DUBLIN_BACKGROUND:'#67afd5');host.dataset.city=city;$('city-name').textContent=cityNames[city];
 host.setAttribute('aria-label',`Interactive 3D ${city[0].toUpperCase()+city.slice(1)} city map`);
 document.querySelectorAll('button[data-city]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.city===city)));
 const tabs=city==='dublin'?[['all','🗺️','All Dublin'],['centre','🏛️','City centre'],['northside','🏘️','Northside'],['docklands','⚓','Docklands']]:city==='abuja'?[['all','🗺️','All Abuja'],['central','🏛️','Central'],['maitama','🌳','Maitama'],['jabi','🌊','Jabi']]:[['all','🗺️','All Lagos'],['mainland','🏘️','Mainland'],['island','🏙️','Island'],['lekki','🌴','Lekki']];
 document.querySelectorAll('[data-district]').forEach((button,i)=>{button.dataset.district=tabs[i][0];button.innerHTML=`${tabs[i][1]}<span>${tabs[i][2]}</span>`;button.classList.toggle('active',i===0);});
 controls.maxDistance=cameraLimits[city].max;controls.minDistance=cameraLimits[city].min;
 const saved=cityCameras[city];const view=saved?normalizeCameraView(saved,cityViews[city],MAP_WORLD_BOUNDS[city],controls.minDistance,controls.maxDistance):cityViews[city];camera.position.copy(view.position);controls.target.copy(view.target);controls.update();clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[city]);updateCameraClipPlanes();
 sun.position.set(city==='lagos'?32:40,city==='lagos'?56:90,city==='lagos'?24:28);const bounds=MAP_WORLD_BOUNDS[city],extent=Math.max(bounds.maxX-bounds.minX,bounds.maxZ-bounds.minZ)*.58;Object.assign(sun.shadow.camera,{left:-extent,right:extent,top:extent,bottom:-extent,near:.5,far:city==='lagos'?140:260});sun.shadow.camera.updateProjectionMatrix();
 marker.position.set(city==='lagos'?.75:0,.28,city==='lagos'?-6:city==='dublin'?5:0);
 publish();return {city,changed:true};
}
function district(p){return p.city!=='lagos'?p.area:p.z< -2?'Mainland':p.x>8?'Lekki':'Island';}
function selectPlace(p){if(p.city!==activeCity)switchCity(p.city);selected=p;labels.forEach(l=>l.button.classList.toggle('selected',l.place===p));$('detail').hidden=false;$('place-name').textContent=`${p.emoji||emoji[p.id]||'🏠'} ${p.name}`;$('district').textContent=district(p);$('place-desc').textContent=p.description||descriptions[p.id]||(p.city==='abuja'?`${p.name} in ${p.area}. Explore the landmark and its surroundings on the Abuja map.`:`${p.name} on the ${district(p)} side of the city.`);selectionRing.position.set(p.x,p.city==='lagos'?.23:.33,p.z);selectionRing.scale.setScalar(p.city!=='lagos'?Math.max(1,Math.min(p.w,p.d)*.55):1);selectionRing.visible=true;publish();}
function clearSelection(){selected=null;$('detail').hidden=true;selectionRing.visible=false;labels.forEach(l=>l.button.classList.remove('selected'));publish();}
function flyTo(x,z,distance=20,targetY=0){const direction=camera.position.clone().sub(controls.target).normalize();transition={from:camera.position.clone(),fromTarget:controls.target.clone(),to:new THREE.Vector3(x,targetY,z).addScaledVector(direction,distance),toTarget:new THREE.Vector3(x,targetY,z),start:performance.now()};}
function focusPlace(place){let distance=place.id==='dubAirport'?90:place.city==='dublin'?Math.max(14,Math.max(place.w,place.d)*2.2,place.h*5):10;const port=place.kind==='seaport',mainPort=place.id==='dubPort';if(place.city==='dublin'){const width=mainPort?60:port?Math.max(place.w||0,place.d||0,24):place.w;distance=Math.max(distance,width/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov)/2)*camera.aspect)*1.1)}flyTo(mainPort?64:place.focusX??place.x,place.focusZ??place.z,mainPort?Math.max(85,distance):port?Math.max(38,distance):distance,place.focusY??(place.city==='dublin'&&place.kind!=='airport'?Math.min(2,place.h*.25):0))}
function walkHeight(x,z){if(activeCity!=='dublin')return .22;const bridgeY=dublinBridges.roadSurfaceY(x,z);const approachY=isOnHowthApproach(x,z)?dublinRoadSurfaceY(x,z):undefined;return(bridgeY??approachY??dublinSecondHarbour.groundY?.(x,z)??dublinPort.groundY?.(x,z)??.25)-.03}
function toggleWalk(value=!walking){walking=value;marker.visible=value;controls.enableRotate=!value;const walkButton=document.getElementById('walk');walkButton?.setAttribute('aria-pressed',String(value));const walkControls=document.getElementById('walk-controls');if(walkControls)walkControls.hidden=!value;const hint=document.getElementById('hint');if(hint)hint.hidden=value;walkTarget=null;keys.clear();if(value)flyTo(marker.position.x,marker.position.z,12);else resetView();publish();}
function resetView(){if(walking){walking=false;marker.visible=false;controls.enableRotate=true;$('walk').setAttribute('aria-pressed','false');$('walk-controls').hidden=true;$('hint').hidden=false;keys.clear();}transition={from:camera.position.clone(),fromTarget:controls.target.clone(),to:cityViews[activeCity].position.clone(),toTarget:cityViews[activeCity].target.clone(),start:performance.now()};document.querySelectorAll('[data-district]').forEach(b=>b.classList.toggle('active',b.dataset.district==='all'));}
function zoom(factor){transition=null;settleCameraControls();camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);const dist=camera.position.distanceTo(controls.target);if(dist<controls.minDistance||dist>controls.maxDistance)camera.position.sub(controls.target).normalize().multiplyScalar(THREE.MathUtils.clamp(dist,controls.minDistance,controls.maxDistance)).add(controls.target);controls.update();clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes();publish();}
setHandler($('plus'),'onclick',()=>zoom(.8));setHandler($('minus'),'onclick',()=>zoom(1.25));setHandler($('reset'),'onclick',resetView);
setHandler($('help'),'onclick',()=> $('help-dialog').showModal());setHandler($('close-help'),'onclick',()=> $('help-dialog').close());
setHandler($('close-detail'),'onclick',clearSelection);setHandler($('focus'),'onclick',()=>selected&&focusPlace(selected));
setHandler($('walk-here'),'onclick',()=>{if(!selected)return;const place=selected;toggleWalk(true);marker.position.set(place.arrivalX??place.x,0,place.arrivalZ??(place.z+place.d/2+.65));marker.position.y=walkHeight(marker.position.x,marker.position.z);flyTo(marker.position.x,marker.position.z,12,marker.position.y);clearSelection()});
setHandler($('leave-walk'),'onclick',()=>toggleWalk(false));
listen(controls,'start',()=>transition=null);listen(controls,'end',()=>{cityCameras[activeCity]={position:camera.position.toArray(),target:controls.target.toArray()};publish()});
listen(window,'keydown',e=>{if(e.key==='Escape'){clearSelection();if(walking)toggleWalk(false);}if(walking&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);}});
listen(window,'keyup',e=>keys.delete(e.key));listen(window,'blur',()=>keys.clear());
const moveMap={up:'w',down:'s',left:'a',right:'d'};document.querySelectorAll('[data-move]').forEach(button=>{listen(button,'pointerdown',e=>{button.setPointerCapture(e.pointerId);keys.add(moveMap[button.dataset.move]);});for(const event of ['pointerup','pointercancel','lostpointercapture'])listen(button,event,()=>keys.delete(moveMap[button.dataset.move]));});
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(), ground=new THREE.Plane(new THREE.Vector3(0,1,0),-.22);let pressStart=null;
listen(canvas,'pointerdown',e=>pressStart=[e.clientX,e.clientY]);
listen(canvas,'pointerup',e=>{if(!pressStart||Math.hypot(e.clientX-pressStart[0],e.clientY-pressStart[1])>7)return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const point=new THREE.Vector3();if(!raycaster.ray.intersectPlane(ground,point))return;if(walking){walkTarget=point;return;}const closest=data.filter(p=>p.city===activeCity&&Math.abs(p.x-point.x)<p.w/2+.3&&Math.abs(p.z-point.z)<p.d/2+.3).sort((a,b)=>Math.hypot(a.x-point.x,a.z-point.z)-Math.hypot(b.x-point.x,b.z-point.z))[0];if(closest)selectPlace(closest);else clearSelection();});
listen(window,'resize',()=>{const {width,height}=dimensions(),wasOverview=camera.position.distanceTo(cityViews[activeCity].position)<.01&&controls.target.distanceTo(cityViews[activeCity].target)<.01;for(const label of labels)measureLabel(label);camera.aspect=width/height;camera.updateProjectionMatrix();refreshCityViews();updateOverviewLimits();controls.maxDistance=cameraLimits[activeCity].max;if(!selected&&!walking&&appliedDistrict==='all'&&wasOverview){camera.position.copy(cityViews[activeCity].position);controls.target.copy(cityViews[activeCity].target);controls.update();clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);cityCameras[activeCity]={position:camera.position.toArray(),target:controls.target.toArray()};publish();}else clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes();});
function isLand(x,z){if(activeCity==='dublin'){if(bridgeSpanAt(x,z)!==undefined)return dublinBridges.roadSurfaceY(x,z)!==undefined;return isOnHowthApproach(x,z)||!!dublinSecondHarbour.isLand?.(x,z)||dublin.isLand(x,z)||!!dublinPort.isLand?.(x,z);}if(activeCity==='abuja')return x>-64&&x<60&&z>-47&&z<48&&((x+36)/8)**2+((z+9)/5)**2>1&&Math.hypot(x-52,z+1)>8&&Math.hypot(x+56,z+8)>6;return (x>-21&&x<21&&z>-20.4&&z< -2.4)||(x>-26.9&&x<-20.8&&z>-20.4&&z< -2.4)||(x>-16.8&&x<8.25&&z>.9&&z<14.4)||(x>8.55&&x<23.1&&z>.6&&z<14.4)||(x>-11.25&&x<25.7&&z>13.8&&z<20.3)||(Math.abs(x+1.2)<.33&&z>-2.4&&z<.9)||(x>7.9&&x<8.6&&Math.abs(z-6)<.35);}
const projection=new THREE.Vector3();const mobile=()=>dimensions().width<700;
function update(time){if(!alive||!cityReady)return;const {width,height}=dimensions();if(frameTimeOffset===null)frameTimeOffset=performance.now()-time;time+=frameTimeOffset;const delta=Math.min((time-lastTime)/1000,.05)||0;lastTime=time;
 if(transition){let t=Math.min((time-transition.start)/650,1),ease=t*t*(3-2*t);camera.position.lerpVectors(transition.from,transition.to,ease);controls.target.lerpVectors(transition.fromTarget,transition.toTarget,ease);if(t===1){transition=null;cityCameras[activeCity]={position:camera.position.toArray(),target:controls.target.toArray()};publish()}}
 if(walking){let x=0,z=0;const forward=new THREE.Vector3().subVectors(controls.target,camera.position);forward.y=0;forward.normalize();const right=new THREE.Vector3(-forward.z,0,forward.x);if(keys.has('w')||keys.has('ArrowUp')){x+=forward.x;z+=forward.z}if(keys.has('s')||keys.has('ArrowDown')){x-=forward.x;z-=forward.z}if(keys.has('d')||keys.has('ArrowRight')){x+=right.x;z+=right.z}if(keys.has('a')||keys.has('ArrowLeft')){x-=right.x;z-=right.z}if(x||z)walkTarget=null;else if(walkTarget){x=walkTarget.x-marker.position.x;z=walkTarget.z-marker.position.z;if(Math.hypot(x,z)<.1)walkTarget=null;}if(x||z){let norm=Math.hypot(x,z),dx=x/norm*delta*(activeCity==='lagos'?2.2:5.8),dz=z/norm*delta*(activeCity==='lagos'?2.2:5.8);const nextX=marker.position.x+dx,nextZ=marker.position.z+dz,alreadyOnDeck=isOnBridgeDeck(marker.position.x,marker.position.z),mayCross=activeCity!=='dublin'||mayEnterBridge({currentlyOnDeck:alreadyOnDeck,signal:dublinBridges.signalAt(nextX,nextZ)});if(isLand(nextX,nextZ)&&mayCross){marker.position.x=nextX;marker.position.z=nextZ;const nextY=walkHeight(marker.position.x,marker.position.z),dy=nextY-marker.position.y;marker.position.y=nextY;camera.position.y+=dy;controls.target.y+=dy;marker.rotation.y=Math.atan2(dx,dz);camera.position.x+=dx;camera.position.z+=dz;controls.target.x+=dx;controls.target.z+=dz;}else walkTarget=null;}}
 controls.update();clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes();camera.updateMatrixWorld();const occupied=[];
 for(const label of labels){projection.copy(label.point).project(camera);const x=(projection.x+1)*width/2,y=(-projection.y+1)*height/2,labelWidth=label.width,edge=label.visible?0:10;let visible=label.place.city===activeCity&&showNames&&projection.z<1&&projection.z>-1&&x>labelWidth/2+8+edge&&x<width-labelWidth/2-8-edge&&y>(mobile()?210:225)+edge&&y<height-100-edge;if(visible&&x>width-78&&Math.abs(y-height/2)<100)visible=false;if(visible&&label.place!==selected){const overlaps=occupied.some(p=>Math.abs(p.x-x)<(p.w+labelWidth)/2+(label.visible?-2:6)&&Math.abs(p.y-y)<(label.visible?23:35));if(overlaps)visible=false;else occupied.push({x,y,w:labelWidth});}label.visible=visible;label.button.hidden=!visible;if(visible)label.button.style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;}
 if(activeCity==='dublin'&&!document.hidden&&!reducedMotion.matches&&!motionPausedForVerification&&!dublinPort.snapshot().paused){dublinElapsed+=delta;advanceDublinSimulation(dublinElapsed);for(let i=0;i<airportRotors.length;i++){if(i%2===0)airportRotors[i].rotation.y=dublinElapsed*15;else airportRotors[i].rotation.x=dublinElapsed*19;}}
 for(let i=0;i<traffic.length;i++)traffic[i].position.x=((time*.001*(i%2?-1:1)+i*6)%30+30)%30-15;
}
const urlCity=new URLSearchParams(location.search).get('city');const requestedCity=['lagos','abuja','dublin'].includes(urlCity)?urlCity:(initialState.city||'lagos');const initialView=initialState.cameraViews?.[activeCity]?normalizeCameraView(initialState.cameraViews[activeCity],cityViews[activeCity],MAP_WORLD_BOUNDS[activeCity],cameraLimits[activeCity].min,cameraLimits[activeCity].max):cityViews[activeCity];cityCameras[activeCity]=initialView;camera.position.copy(initialView.position);controls.target.copy(initialView.target);controls.update();updateCameraClipPlanes();if(['abuja','dublin'].includes(requestedCity))switchCity(requestedCity);const requestedPlace=new URLSearchParams(location.search).get('place')||initialState.selectedId;if(requestedPlace){const initialPlace=data.find(place=>place.id===requestedPlace);if(initialPlace)selectPlace(initialPlace)}
const roadConnectivity=measureRoadConnectivity(DUBLIN_ROAD_NETWORK);
const dublinMetricSnapshot=()=>{const {surfaceSamples,...roads}=dublin.roadDetails?.metrics||dublin.roadDetails||{};const {roadDetails,...city}=dublin.world.userData.metrics||{};return {city:{...city,selectablePlaces:dublin.places.length,placeCategories:dublin.places.reduce((counts,place)=>{const key=place.category||place.kind||'landmark';counts[key]=(counts[key]||0)+1;return counts;},{})},places:dublin.places.map(({id,name,category,kind,x,z})=>({id,name,category,kind,x,z})),sceneObjectNames:dublinSceneObjectNames,roads:{...roads,connectivity:roadConnectivity},airport:dublin.airport?.userData.metrics||null,secondHarbour:dublinSecondHarbour.snapshot(),bridges:dublinBridges.snapshot(),port:dublinPort.world.userData.metrics}};
const snapshot=()=>{clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes();let meshes=0,triangles=0;scene.traverse(node=>{if(node.isMesh){meshes++;triangles+=node.geometry?.index?node.geometry.index.count/3:(node.geometry?.attributes?.position?.count||0)/3}});return {city:activeCity,ready:cityReady,meshes,triangles,selectedId:selected?.id||null,camera:{position:camera.position.toArray(),target:controls.target.toArray(),limits:cameraLimits[activeCity],bounds:MAP_WORLD_BOUNDS[activeCity],near:camera.near,far:camera.far},state:{names:showNames,homes:showHomes,boards:showBoards,walking},walker:walking?marker.position.toArray():null,referenceTrees:dublin.treePlacements?.length||0,dublinClock:{timeSeconds:dublinElapsed,paused:dublinPort.snapshot().paused},dublinMotion:dublinMotion.getSnapshot?.()||dublinMotion.snapshot?.(dublinElapsed)||null,secondHarbour:dublinSecondHarbour.snapshot(),bridges:dublinBridges.snapshot(),port:dublinPort.snapshot(),dublinMetrics:dublinMetricSnapshot()}};
const simulationSnapshot=()=>{clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);updateCameraClipPlanes();return {city:activeCity,ready:cityReady,camera:{position:camera.position.toArray(),target:controls.target.toArray(),limits:cameraLimits[activeCity],bounds:MAP_WORLD_BOUNDS[activeCity],near:camera.near,far:camera.far},state:{names:showNames,homes:showHomes,boards:showBoards,walking},walker:walking?marker.position.toArray():null,dublinClock:{timeSeconds:dublinElapsed,paused:dublinPort.snapshot().paused},dublinMotion:dublinMotion.getSnapshot?.()||dublinMotion.snapshot?.(dublinElapsed)||null,secondHarbour:dublinSecondHarbour.snapshot(),bridges:dublinBridges.snapshot(),port:dublinPort.snapshot()}};
const handle={update,dispose,switchCity,applyState,snapshot,selectPlace:(id)=>{const place=data.find(item=>item.id===id);if(!place)throw new Error(`Unknown map place: ${id}`);selectPlace(place)},getState:()=>{clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);return {city:activeCity,names:showNames,homes:showHomes,boards:showBoards,walking,selectedId:selected?.id||null,selectedPlace:selected?{id:selected.id,name:selected.name,city:selected.city}:null,cameraViews:{...cityCameras,[activeCity]:{position:camera.position.toArray(),target:controls.target.toArray()}},ready:cityReady}}};
let frameTimeOffset=null;
function applyState(state={}){if(!alive)return;applyingState=true;try{if(state.names!==undefined)showNames=!!state.names;if(state.homes!==undefined){showHomes=!!state.homes;estate.visible=activeCity==='lagos'&&showHomes;abuja.homes.visible=showHomes;dublin.homes.visible=showHomes}if(state.boards!==undefined){showBoards=!!state.boards;boards.visible=activeCity==='lagos'&&showBoards;abuja.boards.visible=showBoards;dublin.boards.visible=showBoards}if(state.city&&state.city!==activeCity){switchCity(state.city);appliedDistrict='all'}if(state.cameraViews&&state.cameraViews!==lastCameraViews&&state.cameraViews[activeCity]){settleCameraControls();const view=normalizeCameraView(state.cameraViews[activeCity],cityViews[activeCity],MAP_WORLD_BOUNDS[activeCity],cameraLimits[activeCity].min,cameraLimits[activeCity].max);camera.position.copy(view.position);controls.target.copy(view.target);controls.update();clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity])}lastCameraViews=state.cameraViews||lastCameraViews;if(state.district!==undefined&&state.district!==appliedDistrict){appliedDistrict=state.district;if(state.district==='all')resetView();else{clearSelection();const targets=activeCity==='dublin'?{centre:[-5,12,39],northside:[-7,-20,55],docklands:[48,0,65]}:activeCity==='abuja'?{central:[16,0,45],maitama:[22,-32,43],jabi:[-35,-10,45]}:{mainland:[0,-12,28],island:[-4,7.5,25],lekki:[15,8,24]};if(targets[state.district])flyTo(...targets[state.district])}}if(state.selectedId!==undefined){const place=data.find(item=>item.id===state.selectedId);if(place)selectPlace(place);else clearSelection()}if(state.walking!==undefined&&!!state.walking!==walking)toggleWalk(!!state.walking)}finally{applyingState=false}}
controller.signal.addEventListener('abort',dispose,{once:true});
try{await Promise.all(tasks);assertAlive();dublin.world.traverse(node=>{if(node.name)dublinSceneObjectNames.push(node.name)})}catch(error){dispose();if(!controller.signal.aborted&&taskErrors.length)throw new AggregateError(taskErrors,'One or more map models failed to load',{cause:error});throw error}
await document.fonts?.ready;assertAlive();for(const label of labels)measureLabel(label);cityReady=true;$('loader').hidden=true;host.dataset.runtimeId=instanceId;host.dataset.ready='true';publish();
function dispatchPort(action){if(!alive||activeCity!=='dublin')return {message:'Open Dublin to operate the harbour'};const type=typeof action==='string'?action:action?.type;const result=dublinPort.dispatch(action);if(type==='reset'){dublinPort.update(0,{bridges:dublinBridges});dublinBridges.reset();dublinMotion.update(0,{bridges:dublinBridges});dublinSecondHarbour.update(0);dublinElapsed=0;dublinSimulationTime=0;for(let i=0;i<airportRotors.length;i++){airportRotors[i].rotation.set(0,0,0)}}return result;}
window.__mapExplorer=Object.freeze({getSnapshot:snapshot,dispatchPort,...(process.env.NODE_ENV==='development'?{stressCameraForVerification:({panX=0,panZ=0,zoomFactor=1}={})=>{if(![panX,panZ,zoomFactor].every(Number.isFinite)||zoomFactor<=0)throw new TypeError('Camera stress values must be finite and zoomFactor positive');controls.target.x+=panX;controls.target.z+=panZ;camera.position.x+=panX;camera.position.z+=panZ;camera.position.sub(controls.target).multiplyScalar(zoomFactor).add(controls.target);controls.update();clampCameraToBounds(camera,controls,MAP_WORLD_BOUNDS[activeCity]);return snapshot()},seekDublinSimulation:(seconds)=>{motionPausedForVerification=true;return seekDublinSimulation(seconds)},seekDublinMotion:(seconds)=>{motionPausedForVerification=true;return seekDublinSimulation(seconds)},resumeDublinMotion:()=>{motionPausedForVerification=false}}:{})});
function dispose(){if(!alive)return;publish();alive=false;cityReady=false;controller.abort();for(const cleanup of cleanups.splice(0).reverse())cleanup();controls.dispose();disposeNode(dublin.world);dublinPort.dispose?.();dublinBridges.dispose?.();dublinSecondHarbour.dispose?.();dublinMotion.dispose?.();for(const label of labelNodes)label.remove();labelNodes.length=0;for(const root of runtimeRoots){root.removeFromParent();disposeNode(root)}for(const texture of ownedTextures)texture.dispose();for(const material of ownedMaterials)material.dispose();for(const geometry of ownedGeometries)geometry.dispose();if(previousClearColor)renderer.setClearColor(previousClearColor,previousClearAlpha);renderer.toneMapping=previousRendererState.toneMapping;renderer.toneMappingExposure=previousRendererState.toneMappingExposure;renderer.shadowMap.enabled=previousRendererState.shadowEnabled;renderer.shadowMap.type=previousRendererState.shadowType;if(previousCanvasState.ariaLabel===null)canvas.removeAttribute('aria-label');else canvas.setAttribute('aria-label',previousCanvasState.ariaLabel);if(previousCanvasState.tabIndex===null)canvas.removeAttribute('tabindex');else canvas.setAttribute('tabindex',previousCanvasState.tabIndex);if(host.dataset.runtimeId===instanceId){delete host.dataset.ready;delete host.dataset.runtimeId;if(previousHostState.city===undefined)delete host.dataset.city;else host.dataset.city=previousHostState.city;if(previousHostState.ariaLabel===null)host.removeAttribute('aria-label');else host.setAttribute('aria-label',previousHostState.ariaLabel)}if(window.__mapExplorer?.getSnapshot===snapshot)delete window.__mapExplorer}
if(document.modelContext?.registerTool){const context=document.modelContext;for(const tool of [{name:'switch_map_city',description:'Switch between the Lagos, Abuja and Dublin map views.',inputSchema:{type:'object',properties:{city:{type:'string',enum:['lagos','abuja','dublin']}},required:['city'],additionalProperties:false},execute:input=>switchCity(input?.city)},{name:'list_map_places',description:'List the landmarks in the Lagos, Abuja and Dublin maps.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>data.map(({id,name,city,x,z})=>({id,name,city,x,z}))},{name:'focus_map_place',description:'Select and focus a landmark in the map.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:input=>{const p=data.find(p=>p.id===input?.id);if(!p)throw new Error('Unknown map place');selectPlace(p);focusPlace(p);return {id:p.id,name:p.name,selected:true};}}]){try{await context.registerTool(tool)}catch(e){console.warn('Map tool unavailable',e)}}}
return handle;
}
